'use client';

import { useRuntimeConfig } from '../context/runtime-config-context';

/**
 * Global Usercentrics CMP v3 programmatic API. Exposed as `window.__ucCmp`
 * by the Usercentrics loader; this is the canonical handle the Usercentrics
 * admin dashboard's own snippet generator uses (see the "Privacy Settings"
 * link template in the dashboard).
 */
interface TUcCmp {
    showSecondLayer?: () => void;
}

declare global {
    interface Window {
        __ucCmp?: TUcCmp;
    }
}

/**
 * Opens the Usercentrics "second layer" (detailed settings + cookie
 * declaration) when clicked. Mount this on the privacy policy page (or a
 * dedicated cookie policy page) — required for GDPR Art. 13 / Swiss FMG
 * Art. 45c disclosure.
 *
 * Renders nothing when Usercentrics is not configured for the tenant. No
 * direct equivalent to Cookiebot's `cd.js` auto-rendered table exists in
 * Usercentrics v3; the second layer is the canonical way to show the full
 * cookie list.
 */
export function UsercentricsSecondLayerLink({
    children = 'Open cookie settings',
    className,
}: {
    children?: React.ReactNode;
    className?: string;
}): React.ReactElement | null {
    const { NEXT_PUBLIC_USERCENTRICS_SETTINGS_ID: settingsId } =
        useRuntimeConfig();
    if (!settingsId) return null;

    // Always include `cursor-pointer` so the affordance is visible even when
    // callers pass a className that doesn't imply it. Extra classes from the
    // caller append after so they can override if needed.
    const mergedClassName = ['cursor-pointer', className].filter(Boolean).join(' ');

    return (
        <button
            type="button"
            className={mergedClassName}
            onClick={() => {
                if (typeof window === 'undefined') return;
                // Matches the canonical Usercentrics "Privacy Settings" link
                // generated by their admin dashboard:
                //   <a href="#" onClick="__ucCmp.showSecondLayer();">…</a>
                window.__ucCmp?.showSecondLayer?.();
            }}
        >
            {children}
        </button>
    );
}
