import './global.css';
import { ThemeProvider } from '@maany_shr/e-class-ui-kit/contexts';

export const metadata = {
  title: 'Welcome to platform',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
