import { i18nConfig, TLocale } from '@maany_shr/e-class-translations';
import '../global.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Figtree, Nunito, Raleway, Roboto } from 'next/font/google';
import { notFound } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';
import { auth, viewModels } from '@maany_shr/e-class-models';
import { NextAuthGateway } from '@maany_shr/e-class-auth';
import nextAuth from '../../../lib/infrastructure/server/config/auth/next-auth.config';
import { SessionMonitorWrapper } from '../../../lib/infrastructure/client/components/session-monitor-wrapper';
import {
    languageCodeToLocale,
    localeToLanguageCode,
} from '../../../lib/infrastructure/server/utils/language-mapping';
import Layout from '../../../lib/infrastructure/client/pages/layout';
import { RuntimeConfigProvider } from '../../../lib/infrastructure/client/context/runtime-config-context';
import { connection } from 'next/server';
import env from '../../../lib/infrastructure/server/config/env';
import NextTopLoaderWrapper from '../../../lib/infrastructure/client/components/next-top-loader-wrapper';
import { OTelBrowserProvider } from '../../../lib/infrastructure/client/telemetry';


export const metadata = {
    title: 'Welcome to Platform',
    description: 'Generated by create-nx-workspace',
};

const nunito = Nunito({
    weight: ['300', '400', '700'],
    variable: '--font-nunito',
    subsets: ['latin'],
    display: 'swap',
});
const raleway = Raleway({
    weight: ['300', '400', '700'],
    variable: '--font-raleway',
    subsets: ['latin'],
    display: 'swap',
});
const roboto = Roboto({
    weight: ['300', '400', '700'],
    variable: '--font-roboto',
    subsets: ['latin'],
    display: 'swap',
});
const figtree = Figtree({
    weight: ['300', '400', '700'],
    variable: '--font-figtree',
    subsets: ['latin'],
    display: 'swap',
});

export default async function RootLayout({
    children,
    params: paramsPromise,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // Theme configuration - change this variable to switch themes
    // Available themes: 'just-do-ad', 'job-brand-me', 'bewerbeagentur', 'cms'
    const THEME = 'cms';
    const { languages } = {
        languages: [
            {
                languageCode: 'en',
                name: 'English',
            }
        ],
    };

    // Check if cms's languages are supported
    const availableLocales: TLocale[] = [];
    for (const language of languages) {
        const availableLocale = languageCodeToLocale[language.languageCode];
        if (availableLocale && i18nConfig.locales.includes(availableLocale)) {
            availableLocales.push(availableLocale);
        } else {
            // TODO: might be a soft error
            throw new Error('CMS language is not supported: ' + language.languageCode);
        }
    }

    // Check if the locale is supported
    const params = await paramsPromise;
    const locale = params.locale as TLocale;
    const language = languages.find(
        (value) => value.languageCode === localeToLanguageCode[locale],
    );

    if (!availableLocales.includes(locale) || !language) {
        notFound();
    }

    const messages = await getMessages({ locale });

    // Enable dynamic rendering for runtime environment variables
    // This causes env.ts to be evaluated at request time, not build time
    await connection();

    // Get runtime configuration from env.ts (evaluated at request time due to connection() above)
    const runtimeConfig = {
        NEXT_PUBLIC_E_CLASS_RUNTIME: env.NEXT_PUBLIC_E_CLASS_RUNTIME,
        NEXT_PUBLIC_APP_URL: env.NEXT_PUBLIC_APP_URL,
        NEXT_PUBLIC_E_CLASS_CMS_REST_URL: env.NEXT_PUBLIC_E_CLASS_CMS_REST_URL,
    };

    // OpenTelemetry browser configuration
    // Note: propagateToUrls uses strings (not RegExp) because RegExp can't be serialized to Client Components
    const otelConfig = env.NEXT_PUBLIC_OTEL_ENABLED === 'true' ? {
        serviceName: env.NEXT_PUBLIC_OTEL_SERVICE_NAME || 'e-class-cms-browser',
        otlpEndpoint: env.NEXT_PUBLIC_OTEL_EXPORTER_OTLP_ENDPOINT || '',
        enabled: true,
        propagateToUrls: [
            // Propagate trace headers to CMS REST API (will be converted to RegExp on client side)
            env.NEXT_PUBLIC_E_CLASS_CMS_REST_URL,
        ],
    } : undefined;

    // Authentication is handled in middleware.ts
    // Only authenticated users with admin role can reach this point
    const authGateway = new NextAuthGateway(nextAuth);
    const sessionDTO = await authGateway.getSession();
    let session: auth.TSession | null = null;
    if (sessionDTO.success) {
        session = sessionDTO.data;
    }

    return (
        <html lang={locale}>
            <body
                className={`theme theme-${THEME} ${nunito.variable} ${roboto.variable} ${raleway.variable} ${figtree.variable}`}
            >
                <NextTopLoaderWrapper />
                <SessionProvider session={session}>
                    <NextIntlClientProvider locale={locale} messages={messages}>
                        <RuntimeConfigProvider config={runtimeConfig}>
                            <OTelBrowserProvider config={otelConfig}>
                                <SessionMonitorWrapper locale={locale}>
                                    <Layout availableLocales={availableLocales}>
                                        {children}
                                    </Layout>
                                </SessionMonitorWrapper>
                            </OTelBrowserProvider>
                        </RuntimeConfigProvider>
                    </NextIntlClientProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
