// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/Reviews-Coach-Workspace-bd0adcab71d04c1abc9a71852b879d9c
// Features: listCoachReviews
// UI Components: Footer, Nav bar / Header, SideMenu (Sidebar Navigation), CourseReviewFilterModal
// User Types: Coach
// TSK: TSK-1451

import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../../client/wrappers/default-loading';
import { redirect } from 'next/navigation';
import getSession from '../../config/auth/get-session';
import YourReviews from '../../../client/pages/workspace/your-reviews';
import { HydrateClient, prefetch, trpc } from '../../config/trpc/cms-server';

export default async function YourReviewsServerComponent() {
    const session = await getSession();

    if (!session || !session.user || !session.user.name || !session.user.roles) {
        redirect('/auth/login');
    }

    const roles = session.user.roles;

    // Prefetch coach reviews data
    await Promise.all([
        prefetch(
            trpc.listCoachReviews.queryOptions({
                coachUsername: session.user.name,
            }),
        ),
    ]);

    return (
        <>
            <HydrateClient>
                <Suspense fallback={<DefaultLoadingWrapper />}>
                    <YourReviews roles={roles} />
                </Suspense>
            </HydrateClient>
        </>
    );
}
