packages:
  - 'packages/*'
  - 'apps/*'
overrides:
  jspdf: ^4.2.1
  handlebars: ^4.7.9
  protobufjs: ^7.5.5
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  nx: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
