packages:
  - 'packages/*'
  - 'apps/*'
overrides:
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  jspdf: ^4.2.1
  handlebars: ^4.7.9
  protobufjs: ^7.5.5
allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  nx: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
