// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Manage-Homepage-13a5a7432d018034836ff1ff30ebf200
// Features: getHomePage, saveHomePage, requestFileUpload
// User Types: CMS

import { Suspense } from 'react';
import ManageHomepageServerComponent from '../../../../../../../../lib/infrastructure/server/pages/manage-homepage-rsc';
import DefaultLoadingWrapper from '../../../../../../../../lib/infrastructure/client/wrappers/default-loading';

export default async function ManageHomepagePage({
	params: paramsPromise,
	searchParams: searchParamsPromise,
}: {
	params: Promise<{
		platform_slug: string;
		platform_locale: string;
		locale: string;
	}>;
	searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
	const params = await paramsPromise;
	const searchParams = await searchParamsPromise;

	return (
		<Suspense fallback={<DefaultLoadingWrapper />}>
			<ManageHomepageServerComponent />
		</Suspense>
	);
}
