// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-All-Users-Manage-Users-across-all-platforms-2245a7432d0180658aa3e5d86021683b
// Usecases: listUsers
// Features: FEAT-195 (listUsers - In Progress)
// UI Components: 1 component referenced in Notion (AG Grid for user management)
// User Types: CMS (admin/superadmin - enforced by middleware)
// Tags: AG Grid, users
// Important Note: NO send notifications functionality - users span multiple platforms, notifications require single platform context

import { HydrateClient, prefetch, getServerTRPC } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import AllUsers from '../../client/pages/all-users';
import { TLocale } from '@maany_shr/e-class-translations';
import getSession from '../config/auth/get-session';
import { DefaultNotFound } from '@maany_shr/e-class-ui-kit';

interface AllUsersServerComponentProps {
  locale: TLocale;
}

export default async function AllUsersServerComponent(
  props: AllUsersServerComponentProps
) {
  // Superadmin-only access check
  const session = await getSession();
  const isSuperAdmin = session?.user?.roles?.includes('superadmin') ?? false;

  if (!isSuperAdmin) {
    return <DefaultNotFound locale={props.locale} />
  }

  const trpc = getServerTRPC({
    platform_locale: props.locale,
  });

  // Streaming pattern: Fire prefetch without awaiting (TSK-PERF-007)
  prefetch(trpc.listUsers.queryOptions({
    showFilter: "all"
  }));

  return (
    <HydrateClient>
      <Suspense fallback={<DefaultLoadingWrapper />}>
        <AllUsers
          locale={props.locale}
        />
      </Suspense>
    </HydrateClient>
  );
}
