// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Settings-4fa22586f7044ee28498c561c59d17e0
// Usecases: getPlatform, updatePlatform, requestFileUpload
// Features: Platform configuration management
// UI Components: Nav bar / Header, SideMenu (Sidebar Navigation), SettingsForm
// User Types: CMS

import { HydrateClient, prefetch, getServerTRPC } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import CmsSettings from '../../client/pages/cms-settings';

interface CmsSettingsServerComponentProps {
  locale: string;
  platformSlug: string;
  platformLocale: string;
}

export default async function CmsSettingsServerComponent({
  locale,
  platformSlug,
  platformLocale,
}: CmsSettingsServerComponentProps) {
 
  const trpc = getServerTRPC({
    platform_slug: platformSlug,
    platform_locale: platformLocale,
  });

  // Streaming pattern: Fire prefetch without awaiting (TSK-PERF-007)
  prefetch(trpc.getPlatform.queryOptions({}));
  prefetch(trpc.getEmailConfig.queryOptions({}));

  return (
    <HydrateClient>
      <Suspense fallback={<DefaultLoadingWrapper />}>
        <CmsSettings
          locale={locale}
          platformSlug={platformSlug}
          platformLocale={platformLocale}
        />
      </Suspense>
    </HydrateClient>
  );
}
