// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Coupons-26e5084127d642e0874bca1f789b5e68
// Usecases: listCoupons
// Features: FEAT-177: listCoupons
// UI Components: Nav bar / Header, SideMenu (Sidebar Navigation), List Coupon, Create & Revoke Coupon Modal
// User Types: CMS (admin/superadmin)

import { HydrateClient, prefetch, getServerTRPC } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import Coupons from '../../client/pages/coupons';

interface CouponsServerComponentProps {
  locale: string;
  platformSlug: string;
  platformLocale: string;
}

export default async function CouponsServerComponent({
  locale,
  platformSlug,
  platformLocale,
}: CouponsServerComponentProps) {
  // Get platform-aware TRPC proxy
  const trpc = getServerTRPC({
    platform_slug: platformSlug,
    platform_locale: platformLocale
  });

  // TRPC prefetching for page data using EXACT usecase names from Notion
  // Authentication is handled by middleware - only admin/superadmin can access
  await Promise.all([
    prefetch(trpc.listCoupons.queryOptions({})), // listCoupons
  ]);

  return (
    <HydrateClient>
      <Suspense fallback={<DefaultLoadingWrapper />}>
        <Coupons
          locale={locale}
          platformSlug={platformSlug}
          platformLocale={platformLocale}
        />
      </Suspense>
    </HydrateClient>
  );
}
