// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Create-package-Manage-Packages-f3ea8a52ac704207bdfdec2bacfb37a1
// Title: CMS Create package (Manage Packages)
// Route: /[platform_slug]/packages/create
// User Types: CMS
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6385-175063
// Features: 3 features linked (see Notion)
// UI Components: 9 components linked (see Notion)
// Comments: createPackage creates package in draft state; publishPackage puts it in published state

import { HydrateClient } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import { DefaultLoading } from '@maany_shr/e-class-ui-kit';
import CreatePackage from '../../client/pages/create-package';
import { TLocale } from '@maany_shr/e-class-translations';

interface CreatePackageServerComponentProps {
    locale: TLocale;
    platformSlug: string;
    platformLocale: string;
}

export default async function CreatePackageServerComponent(
    props: CreatePackageServerComponentProps,
) {

    // TODO: Add server-side authentication if needed
    // const session = await getServerSession();
    // Verify user has CMS permissions

    return (
        <>
            <HydrateClient>
                <Suspense
                    fallback={
                        <DefaultLoading
                            locale={props.locale}
                            variant="minimal"
                        />
                    }
                >
                    <CreatePackage
                        locale={props.locale}
                        platformSlug={props.platformSlug}
                        platformLocale={props.platformLocale}
                    />
                </Suspense>
            </HydrateClient>
        </>
    );
}
