// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Edit-package-Manage-Packages-13a5a7432d0180c09247e0f74f3d2907
// Features: updatePackage, getPackage
// UI Components: Package Edit & Achieve Modal
// Comments: Can't change the courses of the package, you only change the data around the package or the pricing

import { TLocale } from '@maany_shr/e-class-translations';
import { HydrateClient, prefetch, getServerTRPC } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import EditPackage from '../../client/pages/edit-package';

interface EditPackageServerComponentProps {
    locale: TLocale;
    platformSlug: string;
    platformLocale: string;
    packageId: string;
}

export default async function EditPackageServerComponent({
    locale,
    platformSlug,
    platformLocale,
    packageId,
}: EditPackageServerComponentProps) {
    const trpc = getServerTRPC({
        platform_slug: platformSlug,
        platform_locale: platformLocale
    });

    const packageIdInt = parseInt(packageId);

    // Streaming pattern: Fire prefetch without awaiting (TSK-PERF-007)
    prefetch(
        trpc.getPackage.queryOptions({
            packageId: packageIdInt,
        })
    );

    return (
        <HydrateClient>
            <Suspense fallback={<DefaultLoadingWrapper />}>
                <EditPackage
                    locale={locale}
                    platformSlug={platformSlug}
                    platformLocale={platformLocale}
                    packageId={packageId}
                />
            </Suspense>
        </HydrateClient>
    );
}
