// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Manage-About-Page-22d5a7432d01808ea977f9b5683a51c7
// Features: getPlatformLanguage, saveAboutPage
// UI Components: RichtextElement (Editor and Viewer)
// User Types: CMS

import ManageAboutPage from '../../client/pages/manage-about-page';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import { HydrateClient, prefetch, getServerTRPC } from '../config/trpc/cms-server';

export default async function ManageAboutPageServerComponent({
	params
}: {
	params: Promise<{
		platform_slug: string;
		platform_locale: string;
		locale: string;
	}>;
}) {
	const resolvedParams = await params;
	const trpc = getServerTRPC(resolvedParams);

	// Prefetch platform language data for the about page editor
	await Promise.all([
		prefetch(trpc.getPlatformLanguage.queryOptions({})),
	]);

	return (
		<>
			<HydrateClient>
				<Suspense fallback={<DefaultLoadingWrapper />}>
					<ManageAboutPage />
				</Suspense>
			</HydrateClient>
		</>
	);
}
