// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Manage-Coaching-Page-25d5a7432d01802cabf7fff03e8d1b9e
// Usecases: getCoachingPage, saveCoachingPage, requestFileUpload
// Features: Manage coaching page content with banner, title, and description
// User Types: CMS (admin/superadmin - enforced by middleware)

import { HydrateClient, prefetch, getServerTRPC } from '../../server/config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import ManageCoachingPage from '../../client/pages/manage-coaching-page';

interface ManageCoachingPageServerComponentProps {
  locale: string;
  platformSlug: string;
  platformLocale: string;
}

export default async function ManageCoachingPageServerComponent({
  locale,
  platformSlug,
  platformLocale,
}: ManageCoachingPageServerComponentProps) {
  // Get platform-aware TRPC proxy
  const trpc = getServerTRPC({
    platform_slug: platformSlug,
    platform_locale: platformLocale,
  });

  // Streaming pattern: Fire prefetch without awaiting (TSK-PERF-007)
  prefetch(trpc.getCoachingPage.queryOptions({})); // getCoachingPage

  return (
    <HydrateClient>
      <Suspense fallback={<DefaultLoadingWrapper />}>
        <ManageCoachingPage
          locale={locale}
          platformSlug={platformSlug}
          platformLocale={platformLocale}
        />
      </Suspense>
    </HydrateClient>
  );
}
