// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Notifications-General-Actions-5ad1adee08f1404e81e452a64cfdecbf
// Usecases: listNotifications, markNotificationsAsRead, listSentNotifications
// Features: FEAT-5 (listNotifications - In Progress), FEAT-95 (markNotificationsAsRead - E2E Mocked), FEAT-213 (listSentNotifications - E2E Mocked)
// UI Components: Nav bar / Header, Tabs (Section Selector), CMS Notification Table / NotificationGrid
// User Types: CMS (admin/superadmin - enforced by middleware)

import { HydrateClient, prefetch, getServerTRPC } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import Notifications from '../../client/pages/notifications';
import { TLocale } from '@maany_shr/e-class-translations';

interface NotificationsServerComponentProps {
  locale: TLocale;
  platformSlug: string;
}

export default async function NotificationsServerComponent(
  props: NotificationsServerComponentProps
) {
  const trpc = getServerTRPC({
    platform_locale: props.locale,
    platform_slug: props.platformSlug,
  });

  await Promise.all([
    prefetch(trpc.listNotifications.queryOptions({})),
    prefetch(trpc.listSentNotifications.queryOptions({})),
  ]);

  return (
    <HydrateClient>
      <Suspense fallback={<DefaultLoadingWrapper />}>
        <Notifications
          locale={props.locale}
          platformSlug={props.platformSlug}
        />
      </Suspense>
    </HydrateClient>
  );
}
