// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-All-Packages-Manage-Packages-13a5a7432d01809c9917d80fe8f7b644

import { TLocale } from '@maany_shr/e-class-translations';
import AllPackagesServerComponent from '../../../../../../../../lib/infrastructure/server/pages/all-packages-rsc';

export default async function AllPackagesPage({
  params: paramsPromise,
}: {
  params: Promise<{ locale: string; platform_slug: string; platform_locale: string }>;
}) {
  const params = await paramsPromise;

  return (
    <AllPackagesServerComponent
      locale={params.locale as TLocale}
      platformSlug={params.platform_slug}
      platformLocale={params.platform_locale as TLocale}
    />
  );
}
