// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Specific-Platform-Users-Manage-Users-d63184e64b3d41f5a780b08567518796

import PlatformUsersServerComponent from '../../../../../../../../lib/infrastructure/server/pages/platform-users-rsc';
import { TLocale } from '@maany_shr/e-class-translations';

export default async function PlatformUsersPage({
  searchParams: searchParamsPromise,
  params: paramsPromise,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
  params: Promise<{ locale: TLocale; platform_slug: string }>;
}) {
  const searchParams = await searchParamsPromise;
  const params = await paramsPromise;

  return (
    <PlatformUsersServerComponent
      locale={params.locale}
      platformSlug={params.platform_slug}
    />
  );
}
