// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Add-Group-Session-View-coach-workspace-11136e9f772641f297768fb72282218a
// TODO: Wire up createGroupCoachingSession usecase when backend implementation is ready

import { TLocale } from '@maany_shr/e-class-translations';
import AddGroupSessionServerComponent from '../../../../../../../../../lib/infrastructure/server/pages/add-group-session-rsc';

export default async function AddGroupSessionPage({
  params: paramsPromise,
}: {
  params: Promise<{ locale: TLocale; course_slug: string; group_id: string }>;
}) {
  const params = await paramsPromise;

  return (
    <AddGroupSessionServerComponent
      locale={params.locale}
      courseSlug={params.course_slug}
      groupId={params.group_id}
    />
  );
}
