// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Add-Group-Session-View-coach-workspace-11136e9f772641f297768fb72282218a
// Usecases: createGroupCoachingSession (NOT IMPLEMENTED), listGroupCoachingSessions, listCoachingOfferings
// User Types: Coach

import { HydrateClient, prefetch, trpc } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import DefaultLoadingWrapper from '../../client/wrappers/default-loading';
import AddGroupSession from '../../client/pages/add-group-session';
import { TLocale } from '@maany_shr/e-class-translations';

interface AddGroupSessionServerComponentProps {
  locale: TLocale;
  courseSlug: string;
  groupId: string;
}

export default async function AddGroupSessionServerComponent(
  props: AddGroupSessionServerComponentProps
) {

  // Streaming pattern: Fire prefetches without awaiting (TSK-PERF-007)
  // React will stream HTML while queries are pending
  prefetch(trpc.getGroupIntroduction.queryOptions({
    courseSlug: props.courseSlug,
    additionalParams: {
      groupId: parseInt(props.groupId),
      requestType: 'requestForCoach',
    },
  }));
  prefetch(trpc.listGroupCoachingSessions.queryOptions({
    groupId: parseInt(props.groupId),
  }));
  prefetch(trpc.listCoachCoachingSessions.queryOptions({}));
  prefetch(trpc.listCoachingOfferings.queryOptions({}));

  return (
    <HydrateClient>
      <Suspense fallback={<DefaultLoadingWrapper />}>
        <AddGroupSession
          locale={props.locale}
          courseSlug={props.courseSlug}
          groupId={props.groupId}
        />
      </Suspense>
    </HydrateClient>
  );
}
