// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/Coach-profile-student-view-book-coaching-outside-courses-4417f760c1a24df8986566bb342a5270
// Features: listCoachReviews, createCourseReview, getCoachIntroduction, getCoachProfileAccess, listCoachCourses
// UI Components: CoachIntroduction, CoachCourses, CoachReviews, BookingButton, CoachAvailability, ProfileHeader, ReviewForm
// User Types: Student

import { HydrateClient, trpc, prefetch } from '../config/trpc/cms-server';
import { Suspense } from 'react';
import { DefaultLoading } from '@maany_shr/e-class-ui-kit';
import CoachProfile from '../../client/pages/coach-profile';
import { TLocale } from '@maany_shr/e-class-translations';
import getSession from '../config/auth/get-session';

interface CoachProfileProps {
	locale: TLocale;
	username: string;
}

export default async function CoachProfileServerComponent(props: CoachProfileProps) {
	// TSK-PERF-014: Get session to match client logic for forStudent parameter
	const session = await getSession();
	const isLoggedIn = !!session?.user;

	// Streaming pattern: Fire prefetches without awaiting (TSK-PERF-007)
	// React will stream HTML while queries are pending
	prefetch(trpc.getCoachIntroduction.queryOptions({ coachUsername: props.username }));
	prefetch(trpc.listCoachReviews.queryOptions({ coachUsername: props.username }));
	// TSK-PERF-014: Match client logic - forStudent depends on login status
	prefetch(trpc.listCoachCourses.queryOptions({ forStudent: isLoggedIn, coachUsername: props.username }));
	prefetch(trpc.getCoachProfileAccess.queryOptions({ coachUsername: props.username }));

	return (
		<>
			<HydrateClient>
				<Suspense fallback={<DefaultLoading locale={props.locale} variant="minimal" />}>
					<CoachProfile locale={props.locale} username={props.username} />
				</Suspense>
			</HydrateClient>
		</>
	);
}
