import { i18nConfig, TLocale } from '@maany_shr/e-class-translations';
import '../global.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Figtree, Nunito, Raleway, Roboto } from 'next/font/google';
import { notFound } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';
import { auth, viewModels } from '@maany_shr/e-class-models';
import type { TGetPlatformUseCaseResponse } from '@dream-aim-deliver/e-class-cms-rest';
import { NextAuthGateway } from '@maany_shr/e-class-auth';
import nextAuth from '../../../lib/infrastructure/server/config/auth/next-auth.config';
import {
    languageCodeToLocale,
    localeToLanguageCode,
} from '../../../lib/infrastructure/server/utils/language-mapping';
import Layout from '../../../lib/infrastructure/client/pages/layout';
import CMSTRPCClientProviders from '../../../lib/infrastructure/client/trpc/cms-client-provider';
import { PlatformProvider } from '../../../lib/infrastructure/client/context/platform-context';
import { getQueryClient, trpc } from '../../../lib/infrastructure/server/config/trpc/cms-server';
import { RuntimeConfigProvider } from '../../../lib/infrastructure/client/context/runtime-config-context';
import { connection } from 'next/server';
import env from '../../../lib/infrastructure/server/config/env';

export const metadata = {
    title: 'Welcome to Platform',
    description: 'Generated by create-nx-workspace',
};

const nunito = Nunito({
    weight: ['300', '400', '700'],
    variable: '--font-nunito',
    subsets: ['latin'],
});
const raleway = Raleway({
    weight: ['300', '400', '700'],
    variable: '--font-raleway',
    subsets: ['latin'],
});
const roboto = Roboto({
    weight: ['300', '400', '700'],
    variable: '--font-roboto',
    subsets: ['latin'],
});
const figtree = Figtree({
    weight: ['300', '400', '700'],
    variable: '--font-figtree',
    subsets: ['latin'],
});

export default async function RootLayout({
    children,
    params: paramsPromise,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // const queryOptions = trpc.listLanguages.queryOptions({});
    // const queryClient = getQueryClient();
    // const languagesResponse = await queryClient.fetchQuery(queryOptions);
    // let languagesViewModel: viewModels.TLanguageListViewModel | undefined;
    // const presenter = createGetLanguagesPresenter((viewModel) => {
    //     languagesViewModel = viewModel;
    // });
    // await presenter.present(languagesResponse, languagesViewModel);
    // if (!languagesViewModel || languagesViewModel.mode !== 'default') {
    //     throw Error(
    //         languagesViewModel?.data?.message ||
    //             'Unknown error happened while loading languages',
    //     );
    // }

    const { languages } = {
        languages: [
            {
                languageCode: 'en',
                name: 'English',
            },
            {
                languageCode: 'de',
                name: 'German',
            },
        ],
    };

    // Check if platform's languages are supported
    const availableLocales: TLocale[] = [];
    for (const language of languages) {
        const availableLocale = languageCodeToLocale[language.languageCode];
        if (availableLocale && i18nConfig.locales.includes(availableLocale)) {
            availableLocales.push(availableLocale);
        } else {
            // TODO: might be a soft error
            throw new Error('A platform language is not supported');
        }
    }

    // Check if the locale is supported
    const params = await paramsPromise;
    const locale = params.locale as TLocale;
    const language = languages.find(
        (value) => value.languageCode === localeToLanguageCode[locale],
    );

    if (!availableLocales.includes(locale) || !language) {
        notFound();
    }

    const messages = await getMessages({ locale });

    // Enable dynamic rendering for runtime environment variables
    // This causes env.ts to be evaluated at request time, not build time
    await connection();

    // Get runtime configuration from env.ts (evaluated at request time due to connection() above)
    const runtimeConfig = {
        NEXT_PUBLIC_E_CLASS_RUNTIME: env.NEXT_PUBLIC_E_CLASS_RUNTIME,
        NEXT_PUBLIC_E_CLASS_PLATFORM_NAME: env.NEXT_PUBLIC_E_CLASS_PLATFORM_NAME,
        NEXT_PUBLIC_APP_URL: env.NEXT_PUBLIC_APP_URL,
        NEXT_PUBLIC_E_CLASS_CMS_REST_URL: env.NEXT_PUBLIC_E_CLASS_CMS_REST_URL,
    };

    // Perform authentication
    const authGateway = new NextAuthGateway(nextAuth);
    const sessionDTO = await authGateway.getSession();
    let session: auth.TSession | null = null;
    if (sessionDTO.success) {
        session = sessionDTO.data;
    }

    // Fetch platform details from database via TRPC
    const queryClient = getQueryClient();
    // @ts-expect-error - fetchQuery returns unknown, but we know the type from TRPC router
    const platformResult: useCaseModels.TGetPlatformUseCaseResponse = await queryClient.fetchQuery(
        trpc.getPlatform.queryOptions({})
    );

    if (!platformResult.success) {
        throw new Error('Failed to load platform data');
    }

    const platform = platformResult.data;

    return (
        <html lang={locale}>
            <body
                className={`${nunito.variable} ${roboto.variable} ${raleway.variable} ${figtree.variable}`}
            >
                <SessionProvider session={session}>
                    <NextIntlClientProvider locale={locale} messages={messages}>
                        <RuntimeConfigProvider config={runtimeConfig}>
                            <PlatformProvider platform={platform}>
                                <CMSTRPCClientProviders>
                                    <Layout availableLocales={availableLocales}>
                                        {children}
                                    </Layout>
                                </CMSTRPCClientProviders>
                            </PlatformProvider>
                        </RuntimeConfigProvider>
                    </NextIntlClientProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
