import { i18nConfig, TLocale } from '@maany_shr/e-class-translations';
import '../global.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Figtree, Nunito, Raleway, Roboto } from 'next/font/google';
import { notFound } from 'next/navigation';
import { SessionProvider } from 'next-auth/react';
import {
    languageCodeToLocale,
    localeToLanguageCode,
} from '../../../lib/infrastructure/server/utils/language-mapping';
import Layout from '../../../lib/infrastructure/client/pages/layout';
import CMSTRPCClientProviders from '../../../lib/infrastructure/client/trpc/cms-client-provider';
import { PlatformProviderWithSuspense } from '../../../lib/infrastructure/client/context/platform-context-with-suspense';
import { HydrateClient, prefetch, trpc } from '../../../lib/infrastructure/server/config/trpc/cms-server';
import { RuntimeConfigProvider } from '../../../lib/infrastructure/client/context/runtime-config-context';
import { Suspense } from 'react';
import getSession from '../../../lib/infrastructure/server/config/auth/get-session';
import { getRuntimeConfig } from '../../../lib/infrastructure/server/utils/get-runtime-config';

export const metadata = {
    title: 'Welcome to Platform',
    description: 'Generated by create-nx-workspace',
};

const nunito = Nunito({
    weight: ['300', '400', '700'],
    variable: '--font-nunito',
    subsets: ['latin'],
});
const raleway = Raleway({
    weight: ['300', '400', '700'],
    variable: '--font-raleway',
    subsets: ['latin'],
});
const roboto = Roboto({
    weight: ['300', '400', '700'],
    variable: '--font-roboto',
    subsets: ['latin'],
});
const figtree = Figtree({
    weight: ['300', '400', '700'],
    variable: '--font-figtree',
    subsets: ['latin'],
});

export default async function RootLayout({
    children,
    params: paramsPromise,
}: {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}) {
    // Performance tracking (development only)
    const perfStart = performance.now();
    const timings: Record<string, number> = {};

    // STEP 1: Locale Resolution and Validation
    const localeStart = performance.now();
    const { languages } = {
        languages: [
            {
                languageCode: 'en',
                name: 'English',
            },
            {
                languageCode: 'de',
                name: 'German',
            },
        ],
    };

    // Check if platform's languages are supported
    const availableLocales: TLocale[] = [];
    for (const language of languages) {
        const availableLocale = languageCodeToLocale[language.languageCode];
        if (availableLocale && i18nConfig.locales.includes(availableLocale)) {
            availableLocales.push(availableLocale);
        } else {
            // TODO: might be a soft error
            throw new Error('A platform language is not supported');
        }
    }

    // Check if the locale is supported
    const params = await paramsPromise;
    const locale = params.locale as TLocale;
    const language = languages.find(
        (value) => value.languageCode === localeToLanguageCode[locale],
    );

    if (!availableLocales.includes(locale) || !language) {
        notFound();
    }
    timings.localeValidation = performance.now() - localeStart;

    // STEP 2: Parallel Data Fetching
    // getMessages and getSession are independent and can run concurrently
    const parallelStart = performance.now();
    const [messages, session] = await Promise.all([
        getMessages({ locale }), // Already cached by next-intl internally
        getSession(), // Uses React.cache() for request-level deduplication
    ]);
    timings.parallelFetch = performance.now() - parallelStart;

    // STEP 3: Runtime Config (synchronous, cached)
    // No connection() needed - getSession() already forces dynamic rendering
    const configStart = performance.now();
    const runtimeConfig = getRuntimeConfig();
    timings.runtimeConfig = performance.now() - configStart;

    // STEP 4: Platform Prefetch (streaming pattern - non-blocking)
    // This fires the query but doesn't await it
    // PlatformProviderWithSuspense will use the prefetched data
    const prefetchStart = performance.now();
    prefetch(trpc.getPlatform.queryOptions({}));
    timings.prefetchStart = performance.now() - prefetchStart;

    // Performance logging (development only)
    const totalTime = performance.now() - perfStart;
    if (process.env.NODE_ENV === 'development') {
        console.log('🚀 Layout Performance:', {
            timings: {
                localeValidation: `${timings.localeValidation.toFixed(2)}ms`,
                parallelFetch: `${timings.parallelFetch.toFixed(2)}ms (messages + session)`,
                runtimeConfig: `${timings.runtimeConfig.toFixed(2)}ms`,
                prefetchStart: `${timings.prefetchStart.toFixed(2)}ms`,
                total: `${totalTime.toFixed(2)}ms`,
            },
            breakdown: {
                parallelFetch: `${((timings.parallelFetch / totalTime) * 100).toFixed(1)}%`,
            }
        });
    }

    return (
        <html lang={locale}>
            <body
                className={`${nunito.variable} ${roboto.variable} ${raleway.variable} ${figtree.variable}`}
            >
                <SessionProvider session={session}>
                    <NextIntlClientProvider locale={locale} messages={messages}>
                        <RuntimeConfigProvider config={runtimeConfig}>
                            <CMSTRPCClientProviders>
                                <HydrateClient>
                                    <Suspense fallback={<div>Loading platform...</div>}>
                                        <PlatformProviderWithSuspense>
                                            <Layout availableLocales={availableLocales}>
                                                {children}
                                            </Layout>
                                        </PlatformProviderWithSuspense>
                                    </Suspense>
                                </HydrateClient>
                            </CMSTRPCClientProviders>
                        </RuntimeConfigProvider>
                    </NextIntlClientProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
