'use client';

// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-All-Packages-Manage-Packages-13a5a7432d01809c9917d80fe8f7b644
// Usecases: listPackages (FEAT-164), archivePackage (FEAT-165)
// User Type: CMS
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6400-219054

import { viewModels } from '@maany_shr/e-class-models';
import { trpc } from '../trpc/cms-client';
import { useListPackagesPresenter } from '../hooks/use-list-packages-presenter';
import { useState } from 'react';
import { TLocale } from '@maany_shr/e-class-translations';
import { useLocale, useTranslations } from 'next-intl';
import { useRouter } from 'next/navigation';
import { 
  DefaultLoading, 
  DefaultError, 
  DefaultNotFound, 
  Outline, 
  PackageCmsCardList, 
  PackageCmsCard, 
  Breadcrumbs, 
  ArchivePackageModal, 
  ArchiveSuccessModal 
} from '@maany_shr/e-class-ui-kit';

interface AllPackagesProps {
  locale: TLocale;
  platformSlug: string;
  platformLocale: string;
}

export default function AllPackages({ locale, platformSlug, platformLocale }: AllPackagesProps) {
  const currentLocale = useLocale() as TLocale;
  const router = useRouter();
  const t = useTranslations('pages.allPackages');
  const breadcrumbsTranslations = useTranslations('components.breadcrumbs');

  // TRPC query for listPackages usecase (FEAT-164)
  const [listPackagesResponse] = trpc.listPackages.useSuspenseQuery({
    platformSlug,
    platformLocale,
  });

  const [listPackagesViewModel, setListPackagesViewModel] = useState<
    viewModels.TListPackagesViewModel | undefined
  >(undefined);

  // Create useListPackagesPresenter hook
  const { presenter } = useListPackagesPresenter(setListPackagesViewModel);

  // Present the data when you have the response
  // @ts-ignore
  presenter.present(listPackagesResponse, listPackagesViewModel);

  // Client state for show archived filter
  const [showArchived, setShowArchived] = useState(false);

  // Modal state
  const [showArchiveModal, setShowArchiveModal] = useState(false);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [packageToArchive, setPackageToArchive] = useState<string | null>(null);

  // Archive package mutation
  const archivePackageMutation = trpc.archivePackage.useMutation({
    onSuccess: () => {
      // Close archive modal and show success modal
      setShowArchiveModal(false);
      setShowSuccessModal(true);
      // Refetch packages by invalidating the query
      trpc.useUtils().listPackages.invalidate({ platformSlug, platformLocale });
    },
    onError: (error) => {
      // TODO: Add toast notification for error
      console.error('Failed to archive package:', error);
    },
  });

  // TODO: Check if publishPackage mutation exists, if not add TODO comment
  // const publishPackageMutation = trpc.publishPackage.useMutation({
  //   onSuccess: () => {
  //     // TODO: Add toast notification for success
  //     trpc.useUtils().listPackages.invalidate({ platformSlug, platformLocale });
  //   },
  //   onError: (error) => {
  //     // TODO: Add toast notification for error
  //     console.error('Failed to publish package:', error);
  //   },
  // });

  // Navigation handlers
  const handleCreatePackage = () => {
    router.push(`/${locale}/platform/${platformSlug}/${platformLocale}/packages/create`);
  };

  const handleEditPackage = (packageId: string) => {
    router.push(`/${locale}/platform/${platformSlug}/${platformLocale}/packages/edit/${packageId}`);
  };

  const handleArchivePackage = (packageId: string) => {
    setPackageToArchive(packageId);
    setShowArchiveModal(true);
  };

  const handleConfirmArchive = () => {
    if (packageToArchive) {
      archivePackageMutation.mutate({ packageId: Number(packageToArchive) });
    }
  };

  const handleCloseArchiveModal = () => {
    setShowArchiveModal(false);
    setPackageToArchive(null);
  };

  const handleCloseSuccessModal = () => {
    setShowSuccessModal(false);
    setPackageToArchive(null);
  };

  const handlePublishPackage = (packageId: string) => {
    // TODO: Implement when publishPackage mutation is available
    console.log('Publish package:', packageId);
  };

  // Breadcrumbs following the standard pattern
  const breadcrumbItems = [
    {
      label: breadcrumbsTranslations('platforms'),
      onClick: () => router.push('/'),
    },
    {
      label: platformSlug.charAt(0).toUpperCase() + platformSlug.slice(1),
      onClick: () => {
        // TODO: Implement navigation to platform
      },
    },
    {
      label: 'Packages',
      onClick: () => {
        // Nothing should happen on clicking the current page
      },
    },
  ];

  // Loading state using discovered patterns
  if (!listPackagesViewModel) {
    return <DefaultLoading locale={currentLocale} variant="minimal" />;
  }

  // Error handling using discovered project patterns
  if (listPackagesViewModel.mode === 'kaboom') {
    const errorData = listPackagesViewModel.data;
    console.error(errorData);
    return <DefaultError locale={currentLocale} />;
  }

  if (listPackagesViewModel.mode === 'not-found') {
    const errorData = listPackagesViewModel.data;
    console.error(errorData);
    return <DefaultNotFound locale={currentLocale} />;
  }

  // Success state - extract data using discovered pattern
  const packagesData = listPackagesViewModel.data;
  const packages = packagesData.packages;

  // Transform package data to match card props
  const transformedPackages = packages.map((pkg: any) => ({
    id: pkg.id,
    title: pkg.title,
    description: pkg.description,
    imageUrl: pkg.imageUrl,
    duration: pkg.duration,
    courseCount: pkg.courseCount || 0,
    pricing: {
      currency: pkg.pricing?.currency || '$',
      fullPrice: pkg.pricing?.fullPrice || pkg.pricing?.actual || 0,
      partialPrice: pkg.pricing?.partialPrice || pkg.pricing?.allCourses || 0,
    },
    status: pkg.status || 'published', // Default to published if status not provided
  }));

  return (
    <div className="flex flex-col space-y-4">
      {/* Breadcrumbs */}
      <Breadcrumbs items={breadcrumbItems} />

      <PackageCmsCardList
        locale={currentLocale}
        packageCount={packages.length}
        showArchived={showArchived}
        onClickCheckbox={() => setShowArchived(!showArchived)}
        onCreatePackage={handleCreatePackage}
      >
        {transformedPackages.map((pkg) => (
          <PackageCmsCard
            key={pkg.id}
            status={pkg.status as 'published' | 'archived'}
            title={pkg.title}
            description={pkg.description}
            imageUrl={pkg.imageUrl}
            duration={pkg.duration}
            courseCount={pkg.courseCount}
            pricing={pkg.pricing}
            locale={currentLocale}
            onClickEdit={() => handleEditPackage(pkg.id)}
            onClickArchive={() => handleArchivePackage(pkg.id)}
            onClickPublished={() => handlePublishPackage(pkg.id)}
          />
        ))}
      </PackageCmsCardList>

      {/* Archive Confirmation Modal */}
      <ArchivePackageModal
        isOpen={showArchiveModal}
        onClose={handleCloseArchiveModal}
        onConfirm={handleConfirmArchive}
        isLoading={archivePackageMutation.isPending}
        locale={currentLocale}
      />

      {/* Archive Success Modal */}
      <ArchiveSuccessModal
        isOpen={showSuccessModal}
        onClose={handleCloseSuccessModal}
        locale={currentLocale}
      />
    </div>
  );
}
