'use client';

// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-List-of-Courses-Manage-Courses-Platform-specific-c9991b9a58e9453db3bacd59e2f2b38e
// Usecases from Notion: listCMSCourses
// Features from Notion: FEAT-115 (listCMSCourses - In Progress)
// User Types from Notion: CMS (admin/superadmin - middleware enforced)
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=7274-218513&t=OB4RQdQpkBV9iLV7-4

import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';
import { trpc } from '../trpc/cms-client';
import { Tabs, CourseCard, CourseCardList, DefaultError, DefaultLoading, SearchInput, CourseCardListSkeleton, Dropdown, Button } from '@maany_shr/e-class-ui-kit';
import { useState, useMemo, useEffect } from 'react';
import { viewModels } from '@maany_shr/e-class-models';
import { useListCmsCoursesPresenter } from '../hooks/use-list-cms-courses-presenter';
import useClientSidePagination from '../utils/use-client-side-pagination';
import { TListCmsCoursesSuccess } from 'packages/models/src/view-models';
import { useRouter, useSearchParams } from 'next/navigation';
import { useRequiredPlatform } from '../context/platform-context';
interface CoursesProps {
  locale: TLocale;
  platformSlug: string;
  platformLocale: string;
}

type Course = TListCmsCoursesSuccess['courses'][number];

export default function Courses({ locale, platformSlug, platformLocale }: CoursesProps) {
  const t = useTranslations('pages.cmsCourses');
  const currentLocale = useLocale() as TLocale;
  const router = useRouter();
  const searchParams = useSearchParams();
  const { platform } = useRequiredPlatform();


  // Get status from URL or default to 'all'
  const statusFromUrl = searchParams.get('status') as 'all' | 'draft' | 'archived' | 'live' | null;
  const [activeTab, setActiveTab] = useState<'all' | 'draft' | 'archived' | 'live'>(
    statusFromUrl && ['all', 'draft', 'archived', 'live'].includes(statusFromUrl) ? statusFromUrl : 'all'
  );

  const [searchQuery, setSearchQuery] = useState<string>('');
  const [isSearchLoading, setIsSearchLoading] = useState<boolean>(false);
  const [searchResults, setSearchResults] = useState<Course[]>([]);
  const [sortOrder, setSortOrder] = useState('desc');
  const [coachingFilter, setCoachingFilter] = useState<'all' | 'with-coaching'>('all');


  useEffect(() => {
    if (statusFromUrl && ['all', 'draft', 'archived', 'live'].includes(statusFromUrl)) {
      setActiveTab(statusFromUrl);
    }
  }, [statusFromUrl]);


  const handleTabChange = (newTab: 'all' | 'draft' | 'archived' | 'live') => {
    setActiveTab(newTab);
    const params = new URLSearchParams(searchParams.toString());
    params.set('status', newTab);
    router.push(`?${params.toString()}`, { scroll: false });
  };

  // Fetch courses data
  const [coursesResponse] = trpc.listCmsCourses.useSuspenseQuery({});

  const [listCoursesViewModel, setListCoursesViewModel] = useState<
    viewModels.TListCmsCoursesViewModel | undefined
  >(undefined);

  const { presenter } = useListCmsCoursesPresenter(
    setListCoursesViewModel
  );

  // Present data when it changes
  useEffect(() => {
    if (coursesResponse && presenter) {
      // @ts-ignore
      presenter.present(coursesResponse, listCoursesViewModel);
    }
  }, [coursesResponse, presenter]);

  const courses: Course[] = listCoursesViewModel?.mode === 'default'
    ? listCoursesViewModel.data.courses
    : [];

  // Filter courses based on active tab and coaching filter
  const filteredCourses = useMemo(() => {
    let result = activeTab === 'all'
      ? courses
      : courses.filter((course: Course) => course.status === activeTab);
    if (coachingFilter === 'with-coaching') {
      result = result.filter((course: Course) => course.coachingSessionCount > 0);
    }
    return result;
  }, [activeTab, courses, coachingFilter]);

  // Memoized sorted filtered courses
  const sortedFilteredCourses = useMemo(() => {
    return [...filteredCourses].sort((a, b) => {
      const aVal = a.rating || 0;
      const bVal = b.rating || 0;
      return sortOrder === 'asc' ? aVal - bVal : bVal - aVal;
    });
  }, [filteredCourses, sortOrder]);

  // Memoized sorted search results
  const sortedSearchResults = useMemo(() => {
    if (searchResults.length === 0 && !searchQuery.trim()) {
      return [];
    }
    return [...searchResults].sort((a, b) => {
      const aVal = a.rating || 0;
      const bVal = b.rating || 0;
      return sortOrder === 'asc' ? aVal - bVal : bVal - aVal;
    });
  }, [searchResults, sortOrder, searchQuery]);

  // Determine which courses to display
  const displayCourses = searchQuery.trim()
    ? sortedSearchResults
    : sortedFilteredCourses;

  // Pagination
  const { displayedItems, hasMoreItems, handleLoadMore } = useClientSidePagination({
    items: displayCourses,
    itemsPerPage: 6,
    itemsPerPage2xl: 8,
  });

  // Loading state
  if (!listCoursesViewModel) {
    return <DefaultLoading locale={currentLocale} variant="minimal" />;
  }

  // Error handling - kaboom error
  if (listCoursesViewModel.mode === 'kaboom') {
    return (
      <DefaultError
        type="simple"
        locale={currentLocale}
        title={t('error.title')}
        description={t('error.description')}
      />
    );
  }

  // Error handling - not found
  if (listCoursesViewModel.mode === 'not-found') {
    return (
      <DefaultError
        type="simple"
        locale={currentLocale}
        title={t('error.notFound.title')}
        description={t('error.notFound.description')}
      />
    );
  }

  const tabs = [
    { value: 'all', label: 'All' },
    { value: 'draft', label: 'Draft' },
    { value: 'live', label: 'Live' },
    { value: 'archived', label: 'Archived' },
  ];

  return (
    <div className="flex flex-col space-y-5 ">
      <div>
        <h1>{t('title')}</h1>
        <p>{t('description')}</p>
      </div>

      <Tabs.Root key={activeTab} defaultTab={activeTab} onValueChange={(value) => handleTabChange(value as typeof activeTab)}>
        <Tabs.List className="flex overflow-auto bg-base-neutral-800 rounded-medium gap-2">
          {tabs.map((tab, index) => (
            <Tabs.Trigger
              key={tab.value}
              value={tab.value}
              isLast={index === tabs.length - 1}
            >
              {tab.label}
            </Tabs.Trigger>
          ))}
        </Tabs.List>

        <div className="mt-5 space-y-4">
          <div className="flex flex-col md:flex-row gap-2 p-2 bg-card-fill rounded-medium border border-card-stroke">
            <div className="flex-1">
              <SearchInput
                key={activeTab}
                items={filteredCourses}
                keys={['title']}
                onResults={(results) => setSearchResults(results)}
                onLoading={(loading) => setIsSearchLoading(loading)}
                onQueryChange={(query) => setSearchQuery(query)}
                placeholder="Search courses..."
              />
            </div>
            <div className="flex gap-2 items-center">
              <Dropdown
                type="simple"
                options={[
                  {
                    label: 'With Feedback',
                    value: 'all',
                  },
                  {
                    label: 'With Coaching Sessions',
                    value: 'with-coaching',
                  },
                ]}
                defaultValue={coachingFilter}
                onSelectionChange={(selected) => {
                  if (selected === 'all' || selected === 'with-coaching') {
                    setCoachingFilter(selected);
                  }
                }}
                text={{ simpleText: 'Filter' }}
              />
            </div>
            <div className="flex gap-2 items-center">
              <label className="text-sm md:text-md text-base-white">
                Sort by:
              </label>
              <Dropdown
                type="simple"
                options={[
                  {
                    label: 'Rating: High to Low',
                    value: 'rating-desc',
                  },
                  {
                    label: 'Rating: Low to High',
                    value: 'rating-asc',
                  },
                ]}
                defaultValue={`rating-${sortOrder}`}
                onSelectionChange={(selected) => {
                  if (typeof selected === 'string') {
                    const order = selected.split('-')[1];
                    setSortOrder(order);
                  }
                }}
                text={{ simpleText: 'Sort by Rating' }}
              />
            </div>
          </div>
        </div>

        {tabs.map((tab) => (
          <Tabs.Content key={tab.value} value={tab.value}>
            <div className="mt-5">
              {isSearchLoading ? (
                <CourseCardListSkeleton />
              ) : (
                <>
                  <CourseCardList
                    locale={currentLocale}
                    emptyStateMessage={'No courses found'}
                  >
                    {displayedItems.map((course) => {

                      const courseMetadata = {
                        title: course.title,
                        imageUrl: course.imageUrl || '',
                        description: "",
                        pricing: {
                          currency: '',
                          fullPrice: 0,
                          partialPrice: 0,
                        },
                        author: {
                          name: `${course.creator.name} ${course.creator.surname}`,
                          image: course.creator.avatarUrl || '',
                        },
                        rating: course.rating || 0,
                        language: course.language,
                        duration: {
                          video: course.duration.video ?? 0,
                          coaching: course.duration.coaching ?? 0,
                          selfStudy: course.duration.selfStudy ?? 0,
                        },
                      };

                      return (
                        <CourseCard
                          key={course.id}
                          userType="course_creator"
                          reviewCount={course.ratingCount}
                          locale={currentLocale}
                          language={course.language}
                          creatorStatus={course.status}
                          course={courseMetadata}
                          sessions={course.coachingSessionCount}
                          sales={course.salesCount}
                          onEdit={() => window.open(`${platform.domainName}/edit/course/${course.slug}`, '_blank')}
                          onGoToOffer={() => window.open(`${platform.domainName}/${platformLocale}/courses/${course.slug}`, '_blank')}
                        />
                      );
                    })}
                  </CourseCardList>

                  {hasMoreItems && (
                    <div className="flex justify-center mt-6">
                      <Button
                        onClick={handleLoadMore}
                        variant="text"
                        size="medium"
                        text="Load More"
                      />
                    </div>
                  )}
                </>
              )}
            </div>
          </Tabs.Content>
        ))}
      </Tabs.Root>
    </div>
  );
}
