'use client';

// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-List-of-Courses-Manage-Courses-Platform-specific-c9991b9a58e9453db3bacd59e2f2b38e
// Usecases from Notion: listCMSCourses
// Features from Notion: FEAT-115 (listCMSCourses - In Progress)
// User Types from Notion: CMS (admin/superadmin - middleware enforced)
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=7274-218513&t=OB4RQdQpkBV9iLV7-4

import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';

interface CoursesProps {
  locale: TLocale;
  platformSlug: string;
}

export default function Courses({ locale, platformSlug }: CoursesProps) {
  const t = useTranslations('pages.cmsCourses');
  const currentLocale = useLocale() as TLocale;

  return (
    <div className="flex flex-col space-y-5 px-30">
      <div>
        <h1>{t('title')}</h1>
        <p>{t('description')}</p>
      </div>

      {/* Features from Notion:
          - FEAT-115 (listCMSCourses - In Progress)
      */}
      {/* UI Components from Notion:
          - 2 components referenced
      */}
    </div>
  );
}
