'use client';

// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Create-package-Manage-Packages-f3ea8a52ac704207bdfdec2bacfb37a1
// Title: CMS Create package (Manage Packages)
// Route: /[platform_slug]/packages/create
// User Types: CMS
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6385-175063
// Features: 3 features linked (see Notion for details)
// UI Components: 9 components linked (see Notion for details)
// Comments: createPackage creates package in draft state; publishPackage puts it in published state

import { useContentLocale } from '../hooks/use-platform-translations';
import { useRequiredPlatformLocale } from '../context/platform-locale-context';
import { useState, useCallback } from 'react';
import { trpc } from '../trpc/cms-client';
import { viewModels } from '@maany_shr/e-class-models';
import { useGetPlatformLanguagePresenter } from '../hooks/use-platform-language-presenter';
import { getAuthorDisplayName } from '../utils/get-author-display-name';
import { useCreatePackagePresenter } from '../hooks/use-create-package-presenter';
import React from 'react';
import {
    Button,
    Stepper,
    Breadcrumbs,
    PackageDetailsStep,
    PackagePricingStep,
    PackageCoursesStep,
    PackagePreviewStep,
} from '@maany_shr/e-class-ui-kit';
import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';
import { useRouter } from 'next/navigation';
import { useSession } from 'next-auth/react';
import { fileMetadata } from '@maany_shr/e-class-models';
import { AccordionBuilderItem } from '@maany_shr/e-class-ui-kit';

// Types for course data
interface CourseData {
    id: string;
    title: string;
    description: string;
    rating: number;
    reviewCount: number;
    language: { code: string; name: string };
    sessions: number;
    duration: { video: number; coaching: number; selfStudy: number };
    sales: number;
    imageUrl: string;
    author: { name: string; image: string };
    pricing: { fullPrice: number; currency: string; partialPrice: number };
}

// Types for pricing configuration
interface PricingConfig {
    completePackageWithCoaching: string;
    completePackageWithoutCoaching: string;
    partialDiscounts: {
        [key: string]: string; // e.g., "2": "20%", "3": "25%", etc.
    };
}

// Types for package preview
interface PackagePreviewData {
    title: string;
    description: string;
    featuredImage: fileMetadata.TFileMetadata | null;
    accordionTitle: string;
    showListItemNumbers: boolean;
    accordionItems: AccordionBuilderItem[];
    selectedCourses: CourseData[];
    pricingConfig: PricingConfig;
    coachingIncluded: boolean;
}

export default function CreatePackage() {
    // Platform context
    const platformContext = useRequiredPlatformLocale();
    const contentLocale = useContentLocale();
    const locale = useLocale() as TLocale;
    const router = useRouter();
    const breadcrumbsTranslations = useTranslations('components.breadcrumbs');
    // const t = useTranslations('components.createPackage');

    // CMS-specific context hooks
    const platformSlug = platformContext.platformSlug;
    const platformLocale = platformContext.platformLocale;

    // Data fetching - platform language (hydrated by RSC)
    const [platformLanguageResponse, { refetch: refetchPlatformLanguage }] = trpc.getPlatformLanguage.useSuspenseQuery({});
    const [platformLanguageViewModel, setPlatformLanguageViewModel] = useState<
        viewModels.TPlatformLanguageViewModel | undefined
    >(undefined);
    const { presenter: platformLanguagePresenter } = useGetPlatformLanguagePresenter(
        setPlatformLanguageViewModel,
    );
    // @ts-ignore
    platformLanguagePresenter.present(platformLanguageResponse, platformLanguageViewModel);

    // Authentication check for CMS users
    const sessionDTO = useSession();
    const session = sessionDTO.data;
    const isLoggedIn = !!session;

    // Multi-step form state
    const [currentStep, setCurrentStep] = useState(1);
    
    // Package details state
    const [packageTitle, setPackageTitle] = useState('');
    const [packageDescription, setPackageDescription] = useState('');
    const [featuredImage, setFeaturedImage] = useState<fileMetadata.TFileMetadata | null>(null);
    
    // Accordion state
    const [accordionTitle, setAccordionTitle] = useState('');
    const [showListItemNumbers, setShowListItemNumbers] = useState(true);
    const [accordionItems, setAccordionItems] = useState<AccordionBuilderItem[]>([]);

    // Course selection state
    const [selectedCourseIds, setSelectedCourseIds] = useState<string[]>(['1', '2']); // Mock: 2 courses selected

    // Pricing state
    const [pricingConfig, setPricingConfig] = useState<PricingConfig>({
        completePackageWithCoaching: '',
        completePackageWithoutCoaching: '',
        partialDiscounts: {
            '2': '',
            '3': '',
            '4': '',
            '5': '',
            '6': '',
            '7': ''
        }
    });

    // Preview state
    const [coachingIncluded, setCoachingIncluded] = useState(true);
    const [isPublishing, setIsPublishing] = useState(false);

    // Courses data from TRPC usecase
    const [coursesResponse] = trpc.listCourses.useSuspenseQuery({ pagination: { page: 1, pageSize: 50 } });
    const allCourses: CourseData[] = (() => {
        if (!coursesResponse.success) return [];
        const payload: any = coursesResponse.data;
        const data = payload?.success ? payload.data : payload;
        const courses: any[] = data?.courses ?? [];
        return courses.map((course) => ({
            id: String(course.id),
            title: course.title,
            description: course.description,
            rating: course.averageRating ?? 0,
            reviewCount: course.reviewCount,
            language: { code: '', name: course.language },
            sessions: course.coachingSessionCount ?? 0,
            duration: { video: 0, coaching: 0, selfStudy: course.fullDuration },
            sales: course.salesCount,
            imageUrl: course.imageUrl ?? '',
            author: {
                name: getAuthorDisplayName(course.author.name, course.author.surname, locale),
                image: course.author.avatarUrl ?? ''
            },
            pricing: {
                fullPrice: course.pricing.withCoaching ?? 0,
                partialPrice: course.pricing.base,
                currency: course.pricing.currency
            }
        }));
    })();


    // File upload handlers
    const handleFeaturedImageUpload = useCallback(async (
        file: fileMetadata.TFileUploadRequest,
        abortSignal?: AbortSignal
    ): Promise<fileMetadata.TFileMetadata> => {
        // TODO: Implement requestFileUpload with uploadType: "upload_package_image"
        // For now, return mock data
        return {
            id: crypto.randomUUID(),
            name: file.name,
            size: file.file.size,
            status: 'available',
            category: 'image',
            url: URL.createObjectURL(file.file),
            thumbnailUrl: URL.createObjectURL(file.file),
        };
    }, []);

    const handleAccordionIconUpload = useCallback(async (
        file: fileMetadata.TFileUploadRequest,
        abortSignal?: AbortSignal
    ): Promise<fileMetadata.TFileMetadata> => {
        // TODO: Implement requestFileUpload with uploadType: "upload_package_accordion_item_icon"
        // For now, return mock data
        return {
            id: crypto.randomUUID(),
            name: file.name,
            size: file.file.size,
            status: 'available',
            category: 'image',
            url: URL.createObjectURL(file.file),
            thumbnailUrl: URL.createObjectURL(file.file),
        };
    }, []);

    // Course management functions
    const toggleCourseSelection = useCallback((courseId: string) => {
        setSelectedCourseIds(prev => 
            prev.includes(courseId) 
                ? prev.filter(id => id !== courseId)
                : [...prev, courseId]
        );
    }, []);

    // Pricing management functions
    const updatePricingConfig = useCallback((updates: Partial<PricingConfig>) => {
        setPricingConfig(prev => ({ ...prev, ...updates }));
    }, []);

    const updatePartialDiscount = useCallback((courseCount: string, discount: string) => {
        setPricingConfig(prev => ({
            ...prev,
            partialDiscounts: {
                ...prev.partialDiscounts,
                [courseCount]: discount
            }
        }));
    }, []);

    // Publish logic
    const handlePublishPackage = useCallback(async () => {
        setIsPublishing(true);
        try {
            // TODO: Implement actual package creation/publishing
            // This would call createPackage mutation with all accumulated data
            console.log('Publishing package with data:', {
                packageTitle,
                packageDescription,
                featuredImage,
                accordionTitle,
                showListItemNumbers,
                accordionItems,
                selectedCourseIds,
                pricingConfig,
                coachingIncluded
            });
            
            // Simulate API call
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            // Redirect to packages list after successful publish
            router.push(`/${locale}/platform/${platformSlug}/${platformLocale}/packages`);
        } catch (error) {
            console.error('Failed to publish package:', error);
            setIsPublishing(false);
        }
    }, [
        packageTitle, packageDescription, featuredImage, accordionTitle, 
        showListItemNumbers, accordionItems, selectedCourseIds, pricingConfig, 
        coachingIncluded, router, locale, platformSlug, platformLocale
    ]);

    // Get selected courses data
    const selectedCourses = allCourses.filter(course => selectedCourseIds.includes(course.id));

    // Pricing calculations
    const calculateIndividualCourseTotal = useCallback(() => {
        return selectedCourses.reduce((total, course) => {
            return total + (coachingIncluded ? course.pricing.fullPrice : course.pricing.partialPrice);
        }, 0);
    }, [selectedCourses, coachingIncluded]);

    const calculatePackagePrice = useCallback(() => {
        const basePrice = coachingIncluded 
            ? pricingConfig.completePackageWithCoaching 
            : pricingConfig.completePackageWithoutCoaching;
        
        // Extract numeric value from price string (e.g., "5400 CHF" -> 5400)
        const numericPrice = parseFloat(basePrice.replace(/[^\d.]/g, '')) || 0;
        return numericPrice;
    }, [pricingConfig, coachingIncluded]);

    const calculateSavings = useCallback(() => {
        const individualTotal = calculateIndividualCourseTotal();
        const packagePrice = calculatePackagePrice();
        return Math.max(0, individualTotal - packagePrice);
    }, [calculateIndividualCourseTotal, calculatePackagePrice]);

    // Breadcrumbs following the standard pattern
    const breadcrumbItems = [
        {
            label: breadcrumbsTranslations('platforms'),
            onClick: () => router.push('/'),
        },
        {
            label: platformSlug.charAt(0).toUpperCase() + platformSlug.slice(1),
            onClick: () => {
                // TODO: Implement navigation to platform
            },
        },
        {
            label: 'Packages',
            onClick: () => {
                router.push(`/${locale}/platform/${platformSlug}/${platformLocale}/packages`);
            },
        },
        {
            label: 'Create Package',
            onClick: () => {
                // Nothing should happen on clicking the current page
            },
        },
    ];

    // Authentication check
    if (!isLoggedIn) {
        router.push(`/${locale}/login`);
        return null;
    }

    const handleNext = () => {
        if (currentStep === 1) {
            setCurrentStep(2); // Move to Courses step
        } else if (currentStep === 2) {
            setCurrentStep(3); // Move to Pricing step
        } else if (currentStep === 3) {
            setCurrentStep(4); // Move to Preview step
        }
    };

    const handleBack = () => {
        if (currentStep === 2) {
            setCurrentStep(1); // Move back to Package Details step
        } else if (currentStep === 3) {
            setCurrentStep(2); // Move back to Courses step
        } else if (currentStep === 4) {
            setCurrentStep(3); // Move back to Pricing step
        }
    };

    const handleDiscard = () => {
        router.push(`/${locale}/platform/${platformSlug}/${platformLocale}/packages`);
    };

        return (
        <div className="flex flex-col space-y-4">
            {/* Breadcrumbs */}
            <Breadcrumbs items={breadcrumbItems} />

            <div className="flex flex-col space-y-2">
                <h1>Create Package</h1>
                <p className="text-text-secondary text-sm">
                    Platform: {platformSlug} | Content Language: {platformLocale.toUpperCase()}
                </p>
            </div>

            {/* Step Navigation */}
            <Stepper.Root 
                key={`stepper-${currentStep}`}
                defaultStep={currentStep} 
                totalSteps={4}
                onStepChange={(step) => setCurrentStep(step)}
            >
                <Stepper.List>
                    <Stepper.Item 
                        step={1} 
                        description="Pkg. Details" 
                    />
                    <Stepper.Item 
                        step={2} 
                        description="Courses" 
                    />
                    <Stepper.Item 
                        step={3} 
                        description="Pricing" 
                    />
                    <Stepper.Item 
                        step={4} 
                        description="Preview" 
                    />
                </Stepper.List>
            </Stepper.Root>

            {/* Step Content */}

            {/* Step 1: Package Details */}
            {currentStep === 1 && (
            <PackageDetailsStep
                    packageTitle={packageTitle}
                    setPackageTitle={setPackageTitle}
                    packageDescription={packageDescription}
                    setPackageDescription={setPackageDescription}
                    featuredImage={featuredImage}
                    setFeaturedImage={setFeaturedImage}
                    accordionTitle={accordionTitle}
                    setAccordionTitle={setAccordionTitle}
                    accordionItems={accordionItems}
                    setAccordionItems={setAccordionItems}
                    handleFeaturedImageUpload={handleFeaturedImageUpload}
                    handleAccordionIconUpload={handleAccordionIconUpload}
                locale={locale}
            />
            )}

            {/* Step 2: Course Selection */}
            {currentStep === 2 && (
            <PackageCoursesStep
                courses={allCourses}
                selectedCourseIds={selectedCourseIds}
                onToggleCourseSelection={toggleCourseSelection}
                locale={locale}
            />
            )}

            {/* Step 3: Pricing Configuration */}
            {currentStep === 3 && (
                <PackagePricingStep
                    pricingConfig={pricingConfig}
                    onUpdatePricingConfig={updatePricingConfig}
                    onUpdatePartialDiscount={updatePartialDiscount}
                />
            )}

            {/* Step 4: Preview and Publish */}
            {currentStep === 4 && (
                <PackagePreviewStep
                    packageTitle={packageTitle || 'Package Title'}
                    packageDescription={packageDescription}
                    featuredImageUrl={featuredImage?.url}
                    durationInMinutes={163}
                    accordionTitle={accordionTitle}
                    showListItemNumbers={showListItemNumbers}
                    accordionItems={accordionItems}
                    selectedCourses={selectedCourses}
                    onExcludeCourse={(id: string) => toggleCourseSelection(id)}
                    coachingIncluded={coachingIncluded}
                    onToggleCoaching={() => setCoachingIncluded(!coachingIncluded)}
                    selectedCoursesTotal={calculateIndividualCourseTotal()}
                    selectedCoursesSavings={calculateSavings()}
                    onBack={handleBack}
                    onPublish={handlePublishPackage}
                    isPublishing={isPublishing}
                    locale={locale}
                    bottomBannerTitle="Buy complete package"
                    bottomBannerSubtitle="Here you get everything included. You can therefore gradually implement your overall appearance with a key visual, new branding, a website and corresponding video content."
                />
            )}

            

            {/* Footer Actions */}
            <div className="flex justify-between pt-6 pb-6">
                {currentStep === 1 ? (
                    <>
                        <Button
                            variant="secondary"
                            size="medium"
                            text="Discard"
                            onClick={handleDiscard}
                        />
                        <Button
                            variant="primary"
                            size="medium"
                            text="Next: Choose courses"
                            onClick={handleNext}
                        />
                    </>
                ) : currentStep === 2 ? (
                    <>
                        <Button
                            variant="secondary"
                            size="medium"
                            text="Back"
                            onClick={handleBack}
                        />
                        <Button
                            variant="primary"
                            size="medium"
                            text="Next: Choose pricing"
                            onClick={handleNext}
                        />
                    </>
                ) : currentStep === 3 ? (
                    <>
                        <Button
                            variant="secondary"
                            size="medium"
                            text="Back"
                            onClick={handleBack}
                        />
                        <Button
                            variant="primary"
                            size="medium"
                            text="Next: Preview"
                            onClick={handleNext}
                        />
                    </>
                ) : currentStep === 4 ? (
                    <>
                        <div className="flex flex-col gap-4 pt-6">
                            <div className="flex flex-col gap-2">
                                <h3 className="text-xl font-semibold text-text-primary">Publish package?</h3>
                                <p className="text-text-secondary">
                                    Does everything look good? If so, go ahead and publish the package. Keep in mind that once a package is published, its courses cannot be changed, so double-check everything before proceeding.
                                </p>
                            </div>
                <div className="flex gap-4">
                                <Button
                                    variant="secondary"
                                    size="medium"
                                    text="No, go back"
                                    onClick={handleBack}
                                />
                                <Button
                                    variant="primary"
                                    size="medium"
                                    text={isPublishing ? 'Publishing...' : 'Yes, publish package'}
                                    onClick={handlePublishPackage}
                                    disabled={isPublishing}
                                />
                            </div>
                </div>
                    </>
                ) : null}
            </div>
        </div>
    );
}
