'use client';

// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Manage-Homepage-13a5a7432d018034836ff1ff30ebf200
// Features: getHomePage, saveHomePage, requestFileUpload
// User Types: CMS
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=5664-69581&t=GjW3V89mle6BrGgh-4

import { trpc } from '../trpc/cms-client';
import { useLocale } from 'next-intl';

import {
	DefaultError,
	DefaultLoading,
	DefaultNotFound,
	Button,
	Tabs,
	Banner
} from '@maany_shr/e-class-ui-kit';
import { viewModels } from '@maany_shr/e-class-models';
import { TLocale } from '@maany_shr/e-class-translations';
import { useEffect, useState, useRef } from 'react';
import { useGetHomePagePresenter } from '../hooks/use-get-home-page-presenter';
import { useContentLocale } from '../hooks/use-platform-translations';
import { useRequiredPlatformLocale } from '../context/platform-locale-context';
import { HeroSection, CarouselSection, CoachingDemandSection, HowItWorksSection } from '@maany_shr/e-class-ui-kit';
import { useHomePageFileUpload } from './common/hooks/use-homepage-file-upload';
import { useHomePageVideoUpload } from './common/hooks/use-homepage-video-upload';
import { useFormState } from 'packages/ui-kit/lib/hooks/use-form-state';


/**
 * ManageHomepage component for CMS
 * Allows admins to manage the homepage content including:
 * - Banner with title, description, video, and thumbnail
 * - Carousel items with text, images, buttons, and badges
 * - Coaching On Demand section
 * - Accordion section
 */
export default function ManageHomepage() {
	// App locale - used for UI elements
	const appLocale = useLocale() as TLocale;

	// Platform context
	const platformContext = useRequiredPlatformLocale();
	const contentLocale = useContentLocale();

	// Fetch homepage data (refetch retained for future integration)
	const [getHomePageResponse, { refetch: refetchHomePage }] = trpc.getHomePage.useSuspenseQuery({});
	const [homePageViewModel, setHomePageViewModel] = useState<
		viewModels.TGetHomePageViewModel | undefined
	>(undefined);

	const { presenter: homePagePresenter } = useGetHomePagePresenter(setHomePageViewModel);

	// Present data on mount and when response changes
	useEffect(() => {
		// @ts-ignore - Presenter doesn't handle progress states
		homePagePresenter.present(getHomePageResponse, homePageViewModel);
	}, [getHomePageResponse, homePagePresenter, homePageViewModel]);

	// Track upload progress
	const [uploadProgress, setUploadProgress] = useState<number | undefined>(undefined);
	const [videoUploadProgress, setVideoUploadProgress] = useState<number | undefined>(undefined);


	const [saveStatus, setSaveStatus] = useState<'idle' | 'success' | 'error'>('idle');
	const [saveMessage, setSaveMessage] = useState<string | null>(null);
	const { handleFileUpload, handleFileDelete, handleFileDownload } = useHomePageFileUpload(setUploadProgress);
	const videoUpload = useHomePageVideoUpload(setVideoUploadProgress);

	// Create default homepage data when it doesn't exist (for upsert functionality)
	const defaultHomePageData: viewModels.TGetHomePageSuccess = {
		banner: {
			title: '',
			description: '',
			videoId: null,
			thumbnailImage: null,
		},
		carousel: [],
		coachingOnDemand: {
			title: '',
			description: '',
			desktopImage: null,
			tabletImage: null,
			mobileImage: null,
		},
		accordion: {
			title: '',
			showNumbers: true,
			items: [],
		},
	};

	// Use actual data if available (mode is 'default'), otherwise use default
	const initialHomePageData = homePageViewModel?.mode === 'default'
		? homePageViewModel.data
		: defaultHomePageData;

	const formState = useFormState<viewModels.TGetHomePageSuccess>(initialHomePageData, { enableReloadProtection: true });
	const isInitializedRef = useRef(false);

	const saveHomePageMutation = trpc.saveHomePage.useMutation({
		onSuccess: (data) => {
			if (data.success) {
				setSaveStatus('success');
				setSaveMessage('Homepage saved successfully!');
				formState.markAsSaved();
				// Don't refetch immediately after save to prevent flickering
				// The form already has the correct data
				// refetchHomePage();
			} else {
				setSaveStatus('error');
				setSaveMessage('Failed to save homepage');
			}
		},
		onError: (error) => {
			setSaveStatus('error');
			setSaveMessage(error.message ?? 'An error occurred while saving');
			console.error('Error saving homepage:', error);
		},

	});

	// Update form state when homepage data loads ONLY on initial load
	// Don't reset form after save to prevent showing stale data
	useEffect(() => {
		if (homePageViewModel?.mode === 'default' && !isInitializedRef.current) {
			formState.setValue(homePageViewModel.data);
			isInitializedRef.current = true;
		}
	}, [homePageViewModel?.mode]);

	// Loading state
	if (!homePageViewModel) {
		return <DefaultLoading locale={appLocale} variant="minimal" />;
	}

	// Error handling - only kaboom errors should prevent rendering
	// Note: 'not-found' is acceptable since save mutation supports upsert

	if (homePageViewModel.mode === 'kaboom') {
		return (
			<DefaultError
				locale={appLocale}
				onRetry={() => {
					refetchHomePage();
				}}
			/>
		);
	}

	// Single state for all homepage data
	const editableHomePageData: viewModels.TGetHomePageSuccess = formState.value!;

	console.log('[ManageHomepage] Rendering with editableHomePageData.banner.title:', editableHomePageData?.banner?.title);

	const handleBannerChange = (banner: typeof editableHomePageData.banner) => {
		formState.setValue({
			...editableHomePageData,
			banner,
		});
	};

	const handleCarouselChange = (carousel: typeof editableHomePageData.carousel) => {
		formState.setValue({
			...editableHomePageData,
			carousel,
		});
	};

	const handleCoachingDemandChange = (coachingOnDemand: typeof editableHomePageData.coachingOnDemand) => {
		formState.setValue({
			...editableHomePageData,
			coachingOnDemand,
		});
	};

	const handleAccordionChange = (accordion: typeof editableHomePageData.accordion) => {
		formState.setValue({
			...editableHomePageData,
			accordion,
		});
	};

	const handleSaveHomePage = () => {
		setSaveStatus('idle');
		setSaveMessage(null);

		saveHomePageMutation.mutate({
			banner: {
				title: editableHomePageData.banner.title,
				description: editableHomePageData.banner.description,
				videoId: editableHomePageData.banner.videoId ? Number(editableHomePageData.banner.videoId) : null,
				thumbnailImageId: editableHomePageData.banner.thumbnailImage?.id ? Number(editableHomePageData.banner.thumbnailImage.id) : null,
			},
			carousel: editableHomePageData.carousel.map(item => ({
				title: item.title,
				description: item.description,
				buttonText: item.buttonText,
				buttonUrl: item.buttonUrl,
				badge: item.badge,
				imageId: item.image?.id ? Number(item.image.id) : null,
			})),
			coachingOnDemand: {
				title: editableHomePageData.coachingOnDemand.title,
				description: editableHomePageData.coachingOnDemand.description,
				desktopImageId: editableHomePageData.coachingOnDemand.desktopImage?.id ? Number(editableHomePageData.coachingOnDemand.desktopImage.id) : null,
				tabletImageId: editableHomePageData.coachingOnDemand.tabletImage?.id ? Number(editableHomePageData.coachingOnDemand.tabletImage.id) : null,
				mobileImageId: editableHomePageData.coachingOnDemand.mobileImage?.id ? Number(editableHomePageData.coachingOnDemand.mobileImage.id) : null,
			},
			accordion: {
				title: editableHomePageData.accordion.title,
				showNumbers: editableHomePageData.accordion.showNumbers,
				items: editableHomePageData.accordion.items.map(item => ({
					title: item.title,
					content: item.content,
					position: item.position,
					iconImageId: item.iconImage?.id ? Number(item.iconImage.id) : null,
				})),
			},
		});
	};

	return (
		<div className="flex flex-col space-y-6 p-6 max-w-7xl mx-auto">
			{/* Page Header */}
			<div className="bg-gradient-to-r from-primary-500 to-primary-600 text-white p-6 rounded-lg shadow-lg">
				<div className="flex justify-between items-center">
					<div>
						<h1 className="text-3xl font-bold mb-2">Manage Homepage</h1>
						<p className="text-lg opacity-90">
							Platform: {platformContext.platformSlug} | Content Language: {contentLocale.toUpperCase()}
						</p>
					</div>
					<Button
						variant="primary"
						size="medium"
						text="Save Changes"
						onClick={handleSaveHomePage}
						disabled={saveHomePageMutation.isPending}

					/>
				</div>
			</div>

			{saveHomePageMutation.isPending && (
				<Banner style="success" title="Saving homepage changes..." />


			)}
			{saveStatus === 'success' && saveMessage && (
				<Banner style="success" title={saveMessage} />
			)
			}
			{
				saveStatus === 'error' && saveMessage && (
					<Banner style="error" title={saveMessage} />
				)
			}

			{/* Tabs for Homepage Sections */}
			<Tabs.Root defaultTab="hero" className="w-full">
				<Tabs.List variant="default">
					<Tabs.Trigger value="hero" isLast={false}>
						Hero Section
					</Tabs.Trigger>
					<Tabs.Trigger value="carousel" isLast={false}>
						Carousel
					</Tabs.Trigger>
					<Tabs.Trigger value="coaching" isLast={false}>
						Coaching On Demand
					</Tabs.Trigger>
					<Tabs.Trigger value="accordion" isLast={true}>
						Accordion
					</Tabs.Trigger>
				</Tabs.List>

				<div className="mt-6">
					<Tabs.Content value="hero">
						<HeroSection
							value={editableHomePageData.banner}
							onChange={handleBannerChange}
							onFileUpload={handleFileUpload}
							onVideoUpload={videoUpload.handleFileChange}
							onFileDelete={handleFileDelete}
							onFileDownload={handleFileDownload}
							uploadProgress={uploadProgress}
							videoUploadProgress={videoUploadProgress}
						/>
					</Tabs.Content>

					<Tabs.Content value="carousel">
						<CarouselSection
							value={editableHomePageData.carousel.map(item => ({ ...item, badge: item.badge ?? undefined }))}
							onChange={handleCarouselChange}
							onFileUpload={handleFileUpload}
							onFileDelete={handleFileDelete}
							onFileDownload={handleFileDownload}
							uploadProgress={uploadProgress}
							uploadType='upload_home_page_carousel_item_image'
						/>
					</Tabs.Content>

					<Tabs.Content value="coaching">
						<CoachingDemandSection
							value={editableHomePageData.coachingOnDemand}
							onChange={handleCoachingDemandChange}
							onFileUpload={handleFileUpload}
							onFileDelete={handleFileDelete}
							onFileDownload={handleFileDownload}
							uploadProgress={uploadProgress}
						/>
					</Tabs.Content>

					<Tabs.Content value="accordion">
						<HowItWorksSection
							value={editableHomePageData.accordion}
							onChange={handleAccordionChange}
							onFileUpload={handleFileUpload}
							onFileDelete={handleFileDelete}
							onFileDownload={handleFileDownload}
							uploadProgress={uploadProgress}
						/>
					</Tabs.Content>
				</div>
			</Tabs.Root>
		</div >
	);
}
