'use client';

// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Manage-Coaching-Page-25d5a7432d01802cabf7fff03e8d1b9e
// Usecases: getCoachingPage, saveCoachingPage, requestFileUpload
// Features: Manage coaching page content with banner (title, description, image, button)
// Upload type: upload_coaching_page_banner_image
// User Types: CMS (admin/superadmin - enforced by middleware)
// Design: Similar to CMS Manage Offers

import { useState, useEffect, useMemo } from 'react';
import { DefaultLoading, DefaultError, Outline, PageTitleSection, BannerSection, Button, Banner } from '@maany_shr/e-class-ui-kit';
import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';
import { trpc } from '../trpc/cms-client';
import { useSession } from 'next-auth/react';
import { viewModels } from '@maany_shr/e-class-models';
import { useGetCoachingPagePresenter } from '../hooks/use-coaching-page-presenter';
import { useHomePageFileUpload } from './common/hooks/use-homepage-file-upload';
import { useFormState } from 'packages/ui-kit/lib/hooks/use-form-state';

type BannerItemType = {
  title: string;
  description: string;
  image: {
    id: string;
    name: string;
    size: number;
    category: 'image';
    downloadUrl: string;
  } | null;
  buttonText: string;
  buttonLink: string;
};

type CoachingPageFormData = {
  title: string;
  description: string;
  banner: BannerItemType;
};

// Static default data - moved outside component for better performance
const DEFAULT_COACHING_PAGE_DATA: CoachingPageFormData = {
  title: '',
  description: '',
  banner: {
    title: '',
    description: '',
    image: null,
    buttonText: '',
    buttonLink: '',
  },
} as const;

interface ManageCoachingPageProps {
  locale: string;
  platformSlug: string;
  platformLocale: string;
}

export default function ManageCoachingPage({
  locale: _locale,
  platformSlug,
  platformLocale,
}: ManageCoachingPageProps) {
  const locale = useLocale() as TLocale;
  const t = useTranslations('pages.manageCoachingPage');

  const [uploadProgress, setUploadProgress] = useState<number | undefined>(undefined);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [coachingPageViewModel, setCoachingPageViewModel] = useState<
    viewModels.TGetCoachingPageViewModel | undefined
  >(undefined);

  // Defensive client-side auth check (middleware already enforces admin/superadmin)
  const sessionDTO = useSession();
  const session = sessionDTO.data;
  const isAdmin =
    session?.user?.roles?.includes('admin') ||
    session?.user?.roles?.includes('superadmin');

  // TRPC query for page data - using EXACT usecase name from Notion
  const [coachingPageResponse, { refetch: refetchCoachingPage }] = trpc.getCoachingPage.useSuspenseQuery({});

  const { presenter: coachingPagePresenter } = useGetCoachingPagePresenter(
    setCoachingPageViewModel
  );

  const initialFormData: CoachingPageFormData = useMemo(() =>
    (coachingPageViewModel?.mode === 'default')
      ? {
        title: coachingPageViewModel.data.title || '',
        description: coachingPageViewModel.data.description || '',
        banner: {
          title: coachingPageViewModel.data.banner?.title || '',
          description: coachingPageViewModel.data.banner?.description || '',
          image: coachingPageViewModel.data.banner?.image || null,
          buttonText: coachingPageViewModel.data.banner?.buttonText || '',
          buttonLink: coachingPageViewModel.data.banner?.buttonLink || '',
        },
      }
      : DEFAULT_COACHING_PAGE_DATA
    , [coachingPageViewModel]);

  const formState = useFormState(initialFormData, { enableReloadProtection: true });
  const setFormValue = formState.setValue;
  const { handleFileUpload, handleFileDelete, handleFileDownload } = useHomePageFileUpload(setUploadProgress);

  const handlePageTitleChange = (newValue: { title: string; description: string }) => {
    setFormValue((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        title: newValue.title,
        description: newValue.description
      };
    });
  };

  const handleBannerChange = (newBanner: BannerItemType) => {
    setFormValue((prev) => {
      if (!prev) return prev;
      return {
        ...prev,
        banner: newBanner,
      };
    });
  };

  const saveCoachingPageMutation = trpc.saveCoachingPage.useMutation({
    onSuccess: async (data) => {
      if (data.success) {
        setSaveStatus('success');
        await refetchCoachingPage();
      }
    },
    onError: () => {
      setSaveStatus('error');
    },
  });

  // Present data on mount and when response changes
  useEffect(() => {
    // @ts-ignore
    coachingPagePresenter.present(coachingPageResponse, coachingPageViewModel);
  }, [coachingPageResponse, coachingPagePresenter]);

  if (coachingPageViewModel?.mode === 'kaboom') {
    return (
      <DefaultError
        locale={locale}
        title={t('error.title')}
        description={t('error.description')}
      />
    );
  }

  // Defensive auth check on client side
  if (!session || !isAdmin) {
    return (
      <DefaultError
        locale={locale}
        title={t('error.unauthorized.title')}
        description={t('error.unauthorized.description')}
      />
    );
  }

  // Loading state - show loading until all data is ready
  if (!coachingPageResponse) {
    return <DefaultLoading locale={locale} variant="minimal" />;
  }

  // Loading state - show loading until viewModels are presented
  if (!coachingPageViewModel) {
    return <DefaultLoading locale={locale} variant="minimal" />;
  }

  // Safety check for formState.value
  if (!formState.value) {
    return <DefaultLoading locale={locale} variant="minimal" />;
  }

  const handleSave = async () => {
    if (!formState.value) return;

    setSaveStatus('idle');

    await saveCoachingPageMutation.mutateAsync({
      title: formState.value.title,
      description: formState.value.description,
      banner: {
        title: formState.value.banner.title,
        description: formState.value.banner.description,
        imageId: Number(formState.value.banner.image?.id) || null,
        buttonText: formState.value.banner.buttonText,
        buttonLink: formState.value.banner.buttonLink,
      },
    });
  };

  return (
    <div className="flex flex-col space-y-5 w-full">
      {/* Page header with translations */}
      <div className="flex justify-between items-start">
        <div className="flex-1">
          <Outline
            title={t('title')}
            description={t('description')}
          />
        </div>
        <div className="ml-4">
          <Button
            variant="primary"
            size="medium"
            text={t('save')}
            onClick={handleSave}
            disabled={saveCoachingPageMutation.isPending || !formState.isDirty}
          />
        </div>
      </div>

      {saveCoachingPageMutation.isPending && saveStatus === 'idle' && (
        <Banner style="success" title={t('savingBanner')} />
      )}
      {saveStatus === 'success' && (
        <Banner style="success" title={t('savedBanner')} />
      )}
      {saveStatus === 'error' && (
        <Banner style="error" title={t('failedBanner')} />
      )}

      {/* Page Title Section */}
      <PageTitleSection
        value={{ title: formState.value.title, description: formState.value.description }}
        onChange={handlePageTitleChange}
        locale={locale}
      />

      {/* Banner Section */}
      <BannerSection
        value={formState.value.banner}
        onChange={handleBannerChange}
        onFileUpload={handleFileUpload}
        onFileDelete={handleFileDelete}
        onFileDownload={handleFileDownload}
        uploadProgress={uploadProgress}
        locale={locale}
      />

    </div>
  );
}
