'use client';

// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Notifications-General-Actions-5ad1adee08f1404e81e452a64cfdecbf
// Usecases from Notion: listNotifications, markNotificationsAsRead, listSentNotifications
// Features from Notion: FEAT-5 (listNotifications - In Progress), FEAT-95 (markNotificationsAsRead - E2E Mocked), FEAT-213 (listSentNotifications - E2E Mocked)
// API Endpoints from Notion:
// User Types from Notion: CMS (admin/superadmin - enforced by middleware)
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=8494-227923

import { useState, useRef, useEffect } from 'react';
import { DefaultLoading, DefaultError, CMSNotificationGrid, Banner } from '@maany_shr/e-class-ui-kit';
import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';
import { trpc } from '../trpc/cms-client';
import { useSession } from 'next-auth/react';
import { viewModels } from '@maany_shr/e-class-models';
import { useListSentNotificationsPresenter } from '../hooks/use-list-sent-notifications-presenter';
import { useListNotificationsPresenter } from '../hooks/use-list-notifications-presenter';

interface NotificationsProps {
  locale: TLocale;
  platformSlug: string;
}

export default function Notifications({ locale, platformSlug }: NotificationsProps) {
  const t = useTranslations('pages.cmsNotifications');
  const currentLocale = useLocale() as TLocale;

  // All hooks must be called at the top level before any conditional returns
  const [receivedNotificationsViewModel, setReceivedNotificationsViewModel] = useState<
    viewModels.TListNotificationsViewModel | undefined
  >(undefined);
  const [sentNotificationsViewModel, setSentNotificationsViewModel] = useState<
    viewModels.TListSentNotificationsViewModel | undefined
  >(undefined);

  // Error state for mutations
  const [mutationError, setMutationError] = useState<string | null>(null);

  // Defensive client-side auth check (middleware already enforces admin/superadmin)
  const sessionDTO = useSession();
  const session = sessionDTO.data;
  const isAdmin = session?.user?.roles?.includes('admin') || session?.user?.roles?.includes('superadmin');

  // TRPC utils for cache invalidation
  const utils = trpc.useUtils();

  // TRPC queries for page data
  const [receivedNotificationsResponse] = trpc.listNotifications.useSuspenseQuery({});
  const [sentNotificationsResponse] = trpc.listSentNotifications.useSuspenseQuery({});

  const { presenter: receivedNotificationsPresenter } = useListNotificationsPresenter(setReceivedNotificationsViewModel);
  const { presenter: sentNotificationsPresenter } = useListSentNotificationsPresenter(setSentNotificationsViewModel);

  const gridRef = useRef<any>(null);

  // Present data using useEffect to ensure it runs once per data fetch
  useEffect(() => {
    // @ts-ignore
    receivedNotificationsPresenter.present(receivedNotificationsResponse, receivedNotificationsViewModel);
  }, [receivedNotificationsResponse, receivedNotificationsPresenter]);

  useEffect(() => {
    // @ts-ignore
    sentNotificationsPresenter.present(sentNotificationsResponse, sentNotificationsViewModel);
  }, [sentNotificationsResponse, sentNotificationsPresenter]);

  const markNotificationsAsReadMutation = trpc.markNotificationsAsRead.useMutation({
    onMutate: () => {
      setMutationError(null);
    },
    onSuccess: async () => {
      setMutationError(null);
      // Invalidate cache to trigger refetch
      await utils.listNotifications.invalidate();
      await utils.listSentNotifications.invalidate();
    },
    onError: (error) => {
      setMutationError(error.message || 'Failed to mark notifications as read');
    }
  });

  // Extract data from view models
  const receivedNotificationsData = receivedNotificationsViewModel?.mode === 'default' ? receivedNotificationsViewModel.data.notifications : [];
  const sentNotificationsData = sentNotificationsViewModel?.mode === 'default' ? sentNotificationsViewModel.data.notifications : [];

  if (receivedNotificationsViewModel?.mode === 'kaboom' || sentNotificationsViewModel?.mode === 'kaboom') {
    return (
      <DefaultError
        type="simple"
        locale={currentLocale}
        title={t('error.title')}
        description={t('error.description')}
      />
    );
  }

  // Defensive auth check on client side
  if (!session || !isAdmin) {
    return (
      <DefaultError
        type="simple"
        locale={currentLocale}
        title={t('error.title')}
        description={t('error.description')}
      />
    );
  }

  // Loading state (defensive check)
  if (!receivedNotificationsResponse || !sentNotificationsResponse) {
    return <DefaultLoading locale={currentLocale} variant="minimal" />;
  }

  const handleMarkAllRead = () => {
    const receivedIds = receivedNotificationsData
      .filter(n => !n.isRead)
      .map(n => Number(n.id))
      .filter((id) => !Number.isNaN(id));
    if (receivedIds.length > 0) {
      markNotificationsAsReadMutation.mutate({ notificationIds: receivedIds });
    }
  };

  const handleMarkSelectedAsRead = (ids: string[]) => {
    const numericIds = ids.map((id) => Number(id)).filter((id) => !Number.isNaN(id));
    if (numericIds.length > 0) {
      markNotificationsAsReadMutation.mutate({ notificationIds: numericIds });
    }
  };

  return (
    <div className="flex flex-col h-[calc(100vh-200px)] space-y-5">
      <div className="flex-shrink-0">
        <h1>{t('title')}</h1>
        <p className="text-text-secondary">{t('description')}</p>
      </div>

      <div className="flex-1 min-h-0">
        <CMSNotificationGrid
          receivedNotifications={receivedNotificationsData}
          sentNotifications={sentNotificationsData}
          onMarkAllRead={handleMarkAllRead}
          onMarkSelectedAsRead={handleMarkSelectedAsRead}
          onRowClicked={(notification) => {
            if (notification.type === 'received' && !notification.isRead && notification.id) {
              handleMarkSelectedAsRead([notification.id]);
            }
          }}
          gridRef={gridRef}
          locale={currentLocale}
          loading={markNotificationsAsReadMutation.isPending}
        />
      </div>

      {mutationError && (
        <Banner
          title={t('error.mutation.title')}
          description={mutationError}
          style="error"
          icon={true}
          closeable={true}
          onClose={() => setMutationError(null)}
        />
      )}
    </div>
  );
}
