// Auto-generated by page-scaffold command
// TSK: TSK-1
// Features: listTopics, getProfessionalProfile, saveProfessionalProfile
// Route: /workspace/profile

import ProfileServerComponent from '../../../../../lib/infrastructure/server/pages/profile-rsc';

export default async function ProfilePage({
	searchParams: searchParamsPromise,
	params: paramsPromise,
}: {
	searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
	params: Promise<{ locale: string }>;
}) {
	const searchParams = await searchParamsPromise;
	const params = await paramsPromise;

	return <ProfileServerComponent locale={params.locale} />;
}
