// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Manage-Categories-13a5a7432d01807da446eb7172031fcd
// TSK: TSK-1420

import { Suspense } from 'react';
import ManageCategoriesServerComponent from '../../../../../../../../lib/infrastructure/server/pages/manage-categories-rsc';
import DefaultLoadingWrapper from '../../../../../../../../lib/infrastructure/client/wrappers/default-loading';

export default async function ManageCategoriesPage({
    params: paramsPromise,
    searchParams: searchParamsPromise,
}: {
    params: Promise<{
        platform_slug: string;
        platform_locale: string;
        locale: string;
    }>;
    searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
    const params = await paramsPromise;
    const searchParams = await searchParamsPromise;

    return (
        <ManageCategoriesServerComponent
            platformSlug={params.platform_slug}
            platformLocale={params.platform_locale}
            locale={params.locale}
        />
    );
}
