// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Edit-package-Manage-Packages-13a5a7432d0180c09247e0f74f3d2907
// Features: updatePackage, getPackage
// UI Components: Package Edit & Achieve Modal
// Comments: Can't change the courses of the package, you only change the data around the package or the pricing

import { TLocale } from '@maany_shr/e-class-translations';
import EditPackageServerComponent from '../../../../../../../../../../lib/infrastructure/server/pages/edit-package-rsc';

export default async function EditPackagePage({
    params: paramsPromise,
}: {
    params: Promise<{
        locale: string;
        platform_slug: string;
        platform_locale: string;
        packageId: string;
    }>;
}) {
    const params = await paramsPromise;

    return (
        <EditPackageServerComponent
            locale={params.locale as TLocale}
            platformSlug={params.platform_slug}
            platformLocale={params.platform_locale as TLocale}
            packageId={params.packageId}
        />
    );
}
