// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Coupons-26e5084127d642e0874bca1f789b5e68

import CouponsServerComponent from '../../../../../../../../lib/infrastructure/server/pages/coupons-rsc';

export default async function CouponsPage({
  params: paramsPromise,
}: {
  params: Promise<{
    locale: string;
    platform_slug: string;
    platform_locale: string;
  }>;
}) {
  const params = await paramsPromise;
  const { locale, platform_slug, platform_locale } = params;

  return (
    <CouponsServerComponent
      locale={locale}
      platformSlug={platform_slug}
      platformLocale={platform_locale}
    />
  );
}
