// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Package-sale-page-Offers-44cd9de337d442cc8acd4fe25fddd386
// Usecases: getPackageWithCourses, listPackageRelatedPackages
// Features: Display package details with courses, Show related packages, Login prompt for unregistered users

import PackageServerComponent from '../../../../../lib/infrastructure/server/pages/package-rsc';
import { TLocale } from '@maany_shr/e-class-translations';

export default async function PackagePage({
  searchParams: searchParamsPromise,
  params: paramsPromise,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
  params: Promise<{ locale: string; package_id: string }>;
}) {
  const searchParams = await searchParamsPromise;
  const params = await paramsPromise;

  return <PackageServerComponent locale={params.locale as TLocale} packageId={params.package_id} />;
}
