// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/CMS-Single-user-Manage-Users-13a5a7432d018065bea7fcc7370b0adf?v=3ff9feb636a44c81a7e270eced25ebce&source=copy_link

import { TLocale } from '@maany_shr/e-class-translations';
import SingleUserServerComponent from '../../../../../../../../../lib/infrastructure/server/pages/single-user-rsc';

export default async function SingleUserPage({
  searchParams: searchParamsPromise,
  params: paramsPromise,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
  params: Promise<{ locale: string; platform_slug: string; platform_locale: string; username: string }>;
}) {
  const searchParams = await searchParamsPromise;
  const params = await paramsPromise;

  return <SingleUserServerComponent
    locale={params.locale as TLocale}
    platformSlug={params.platform_slug}
    platformLocale={params.platform_locale as TLocale}
    username={params.username}
  />;
}
