// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Order-history-Orders-Payments-Student-workspace-6bb2794c7331418e8fbbf83c40dcb1e5
// Usecases: listUserIncomingTransactions, generateInvoicePdf

import { TLocale } from '@maany_shr/e-class-translations';
import OrderHistoryServerComponent from '../../../../lib/infrastructure/server/pages/order-history-rsc';

export default async function OrderHistoryPage({
  searchParams: searchParamsPromise,
  params: paramsPromise,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
  params: Promise<{ locale: TLocale }>;
}) {
  const searchParams = await searchParamsPromise;
  const params = await paramsPromise;
  const { locale } = params;

  return <OrderHistoryServerComponent locale={locale} />;
}
