// Auto-generated by page-scaffold command v2 - Refactored
// Notion: https://www.notion.so/Order-history-Orders-Payments-Student-workspace-6bb2794c7331418e8fbbf83c40dcb1e5
// Usecases: listUserIncomingTransactions, generateInvoicePdf (Student), listUserOutgoingTransactions (Coach)
// Updated: Refactored to Billing page with role-based tabs (order-history, received-payments)

import { TLocale } from '@maany_shr/e-class-translations';
import BillingServerComponent from '../../../../../lib/infrastructure/server/pages/billing-rsc';

export default async function BillingPage({
  searchParams: searchParamsPromise,
  params: paramsPromise,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
  params: Promise<{ locale: string }>;
}) {
  const searchParams = await searchParamsPromise;
  const params = await paramsPromise;
  const locale = params.locale as TLocale;

  // Extract tab parameter for coach navigation
  let tab = searchParams.tab;
  if (tab && Array.isArray(tab)) {
    tab = undefined;
  }

  return <BillingServerComponent locale={locale} tab={tab as string | undefined} />;
}
