// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Manage-Topics-13a5a7432d0180078589efbb54a14f5b
// TSK: TSK-1393

import { Suspense } from 'react';
import ManageTopicsServerComponent from '../../../../../../../../lib/infrastructure/server/pages/manage-topics-rsc';
import DefaultLoadingWrapper from '../../../../../../../../lib/infrastructure/client/wrappers/default-loading';

export default async function ManageTopicsPage({
    params: paramsPromise,
    searchParams: searchParamsPromise,
}: {
    params: Promise<{
        platform_slug: string;
        platform_locale: string;
        locale: string;
    }>;
    searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
    const params = await paramsPromise;
    const searchParams = await searchParamsPromise;

    return (
        <ManageTopicsServerComponent
            platformSlug={params.platform_slug}
            platformLocale={params.platform_locale}
            locale={params.locale}
        />
    );
}
