// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Group-Workspace-Student-1ff5a7432d01800aa7c2f8a6005e32ee
// Usecases: getGroupIntroduction, listGroupAssignments, getGroupNextCoachingSession, listGroupMembers, getGroupNotes

import { TLocale } from '@maany_shr/e-class-translations';
import GroupWorkspaceServerComponent from '../../../../../../lib/infrastructure/server/pages/group-workspace-rsc';

export default async function GroupWorkspacePage({
  searchParams: searchParamsPromise,
  params: paramsPromise,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
  params: Promise<{ locale: string; slug: string }>;
}) {
  const searchParams = await searchParamsPromise;
  const params = await paramsPromise;

  return <GroupWorkspaceServerComponent locale={params.locale as TLocale} courseSlug={params.slug} />;
}
