// Auto-generated by page-scaffold command
// Notion: https://www.notion.so/CMS-Coaching-Offering-8867dde6ea234a6898dd28783eed06ed
// TSK: TSK-1423

import CoachingOfferingServerComponent from '../../../../../../../../lib/infrastructure/server/pages/coaching-offering-rsc';

export default async function CoachingOfferingPage({
    searchParams: searchParamsPromise,
    params: paramsPromise,
}: {
    searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
    params: Promise<{
        locale: string;
        platform_slug: string;
        language: string;
        platform_locale: string;
    }>;
}) {
    const searchParams = await searchParamsPromise;
    const params = await paramsPromise;

    return (
        <CoachingOfferingServerComponent
            locale={params.locale}
            platformSlug={params.platform_slug}
            language={params.language}
            platformLocale={params.platform_locale}
        />
    );
}
