'use client';

// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Add-Group-Session-View-coach-workspace-11136e9f772641f297768fb72282218a
// Usecases from Notion: createGroupCoachingSession, listGroupCoachingSessions, listCoachingOfferings
// User Types from Notion: Coach

import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import React, { useState, useEffect } from 'react';
import { trpc } from '../trpc/cms-client';
import { viewModels } from '@maany_shr/e-class-models';
import {
    Breadcrumbs,
    DefaultError,
    DefaultLoading,
    Tabs,
    CalendarNavigationHeader,
    Divider,
    Button,
} from '@maany_shr/e-class-ui-kit';
import { AddGroupSessionDialog } from './workspace/calendar/components/add-group-session-dialog';
import { SessionDetailsDialog } from './workspace/calendar/components/session-details-dialog';
import {
    MonthlyGroupCoachingCalendarWrapper,
    WeeklyGroupCoachingCalendarWrapper,
} from './common/group-coaching-calendar-wrappers';
import { useListGroupCoachingSessionsPresenter } from '../hooks/use-list-group-coaching-sessions-presenter';
import { useListCoachCoachingSessionsPresenter } from '../hooks/use-list-coach-coaching-sessions-presenter';
import { useGetGroupIntroductionPresenter } from '../hooks/use-get-group-introduction-presenter';
import { z } from 'zod';

// TODO: Wire up createGroupCoachingSession usecase when it's implemented
// Type definition for createGroupCoachingSession (NOT IMPLEMENTED)
// This type guides the future implementation when the usecase is ready
export const CreateGroupCoachingSessionRequest = z.object({
  groupId: z.number(),
  startTime: z.string().datetime({ offset: true }),
  coachingOfferingTitle: z.string(),
  coachingOfferingDuration: z.number(),
  coachId: z.number(),
});

export type CreateGroupCoachingSessionRequest = z.infer<typeof CreateGroupCoachingSessionRequest>;

// Response: nothing (void) - the operation just succeeds or fails

interface AddGroupSessionProps {
  locale: TLocale;
  courseSlug: string;
  groupId: string;
}

function CalendarContent({ courseSlug, groupId, coachUsername }: { courseSlug: string; groupId: string; coachUsername: string }) {
    const locale = useLocale() as TLocale;
    const t = useTranslations('pages.calendarPage');
    const [currentDate, setCurrentDate] = useState<Date | undefined>(undefined);
    const [currentView, setCurrentView] = useState<'weekly' | 'monthly'>(
        'weekly',
    );

    // Initialize date on client side only to avoid hydration mismatch
    useEffect(() => {
        setCurrentDate(new Date());
    }, []);
    const [selectedDate, setSelectedDate] = useState<Date | undefined>(
        undefined,
    );
    const [newSessionStart, setNewSessionStart] = useState<Date | undefined>(
        undefined,
    );

    const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
    const [scrollToHour, setScrollToHour] = useState<number | undefined>(undefined);
    const [scrollKey, setScrollKey] = useState(0);

    const [isSessionDetailsDialogOpen, setIsSessionDetailsDialogOpen] = useState(false);
    const [chosenSession, setChosenSession] = useState<{
        id: number;
        title: string;
        startTime: Date;
        endTime: Date;
    } | undefined>(undefined);

    // Fetch group coaching sessions for this specific group
    const [groupCoachingSessionsResponse, { refetch: refetchGroupSessions }] =
        trpc.listGroupCoachingSessions.useSuspenseQuery({
            groupId: parseInt(groupId),
        });
    const [groupCoachingSessionsViewModel, setGroupCoachingSessionsViewModel] =
        useState<viewModels.TListGroupCoachingSessionsViewModel | undefined>(undefined);
    const { presenter: groupSessionsPresenter } = useListGroupCoachingSessionsPresenter(
        setGroupCoachingSessionsViewModel,
    );

    // Fetch coach's individual coaching sessions
    const [coachCoachingSessionsResponse, { refetch: refetchCoachSessions }] =
        trpc.listCoachCoachingSessions.useSuspenseQuery({});
    const [coachCoachingSessionsViewModel, setCoachCoachingSessionsViewModel] =
        useState<viewModels.TListCoachCoachingSessionsViewModel | undefined>(undefined);
    const { presenter: coachSessionsPresenter } = useListCoachCoachingSessionsPresenter(
        setCoachCoachingSessionsViewModel,
    );

    // Present data to view models using useEffect
    useEffect(() => {
        if (groupCoachingSessionsResponse) {
            // @ts-ignore - Follow standard pattern used throughout codebase
            groupSessionsPresenter.present(groupCoachingSessionsResponse, groupCoachingSessionsViewModel);
        }
    }, [groupCoachingSessionsResponse, groupSessionsPresenter, groupCoachingSessionsViewModel]);

    useEffect(() => {
        if (coachCoachingSessionsResponse) {
            // @ts-ignore - Follow standard pattern used throughout codebase
            coachSessionsPresenter.present(coachCoachingSessionsResponse, coachCoachingSessionsViewModel);
        }
    }, [coachCoachingSessionsResponse, coachSessionsPresenter, coachCoachingSessionsViewModel]);    const handleGroupSessionAdded = (sessionStartTime: Date) => {
        refetchGroupSessions();
        refetchCoachSessions();
        setIsAddDialogOpen(false);
        setNewSessionStart(undefined);
        setCurrentDate(sessionStartTime);
        setScrollToHour(sessionStartTime.getHours());
        setScrollKey((prev) => prev + 1);
    };

    const handleNewSessionStart = (startTime: Date) => {
        setNewSessionStart(startTime);
        setIsAddDialogOpen(true);
    };

    const handleSessionClick = (sessionId: number) => {
        let found: { id: number; title: string; startTime: string; endTime: string } | undefined;

        if (groupCoachingSessionsViewModel?.mode === 'default') {
            const session = groupCoachingSessionsViewModel.data.sessions.find(s => s.id === sessionId);
            if (session) {
                found = { id: Number(session.id), title: session.course?.title || 'Group Session', startTime: session.startTime, endTime: session.endTime };
            }
        }
        if (!found && coachCoachingSessionsViewModel?.mode === 'default') {
            const session = coachCoachingSessionsViewModel.data.sessions.find(s => s.id === sessionId);
            if (session) {
                found = { id: Number(session.id), title: session.coachingOfferingTitle, startTime: session.startTime, endTime: session.endTime };
            }
        }
        if (!found) return;

        setChosenSession({
            id: found.id,
            title: found.title,
            startTime: new Date(found.startTime),
            endTime: new Date(found.endTime),
        });
        setIsSessionDetailsDialogOpen(true);
    };

    const handleSessionCancelSuccess = () => {
        refetchGroupSessions();
        refetchCoachSessions();
        setIsSessionDetailsDialogOpen(false);
        setChosenSession(undefined);
    };

    if (!groupCoachingSessionsViewModel || !coachCoachingSessionsViewModel || !currentDate) {
        return <DefaultLoading locale={locale} />;
    }

    if (groupCoachingSessionsViewModel.mode !== 'default' || coachCoachingSessionsViewModel.mode !== 'default') {
        return (
            <DefaultError
                type="simple"
                locale={locale}
                title={t('loadError.title')}
                description={t('loadError.description')}
            />
        );
    }

    return (
        <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between mt-4">
                <h3>{t('groupCoachingTitle')}</h3>
                <Button 
                    variant="primary" 
                    text={t('addGroupSessionButton')} 
                    onClick={() => setIsAddDialogOpen(true)}
                />
            </div>
            <Divider className="my-4" />

            <AddGroupSessionDialog
                isOpen={isAddDialogOpen}
                onOpenChange={setIsAddDialogOpen}
                onSuccess={handleGroupSessionAdded}
                initialStartTime={newSessionStart}
                groupId={parseInt(groupId)}
                coachUsername={coachUsername}
            />

            {chosenSession && (
                <SessionDetailsDialog
                    isOpen={isSessionDetailsDialogOpen}
                    onOpenChange={setIsSessionDetailsDialogOpen}
                    sessionId={chosenSession.id}
                    sessionTitle={chosenSession.title}
                    startTime={chosenSession.startTime}
                    endTime={chosenSession.endTime}
                    onCancelSuccess={handleSessionCancelSuccess}
                />
            )}

            <Tabs.Root
                defaultTab="weekly"
                onValueChange={(value) =>
                    setCurrentView(value as 'weekly' | 'monthly')
                }
            >
                <div className="flex flex-col h-full">
                    {/* Desktop view with header and calendar */}
                    <div className="h-[calc(100dvh-300px)] flex-row hidden md:flex">
                        <div className="w-full rounded-lg bg-card-fill p-4 flex flex-col overflow-hidden">
                            <CalendarNavigationHeader
                                currentDate={currentDate}
                                setCurrentDate={setCurrentDate}
                                locale={locale}
                                viewType={currentView}
                                onDateClick={(date) => setSelectedDate(date)}
                                userRole="coach"
                                viewTabs={
                                    <Tabs.List className="bg-base-neutral-800 border border-base-neutral-700">
                                        <Tabs.Trigger
                                            value="weekly"
                                            isLast={false}
                                        >
                                            {t('weeklyView')}
                                        </Tabs.Trigger>
                                        <Tabs.Trigger
                                            value="monthly"
                                            isLast={true}
                                        >
                                            {t('monthlyView')}
                                        </Tabs.Trigger>
                                    </Tabs.List>
                                }
                            />
                            <Tabs.Content
                                value="weekly"
                                className="flex-1 min-h-0"
                            >
                                <WeeklyGroupCoachingCalendarWrapper
                                    groupCoachingSessionsViewModel={groupCoachingSessionsViewModel}
                                    coachCoachingSessionsViewModel={coachCoachingSessionsViewModel}
                                    currentDate={currentDate}
                                    setCurrentDate={setCurrentDate}
                                    selectedDate={selectedDate}
                                    setSelectedDate={setSelectedDate}
                                    setNewSessionStart={handleNewSessionStart}
                                    onSessionClick={handleSessionClick}
                                    scrollToHour={scrollToHour}
                                    scrollKey={scrollKey}
                                />
                            </Tabs.Content>
                            <Tabs.Content
                                value="monthly"
                                className="flex-1 min-h-0"
                            >
                                <MonthlyGroupCoachingCalendarWrapper
                                    groupCoachingSessionsViewModel={groupCoachingSessionsViewModel}
                                    coachCoachingSessionsViewModel={coachCoachingSessionsViewModel}
                                    currentDate={currentDate}
                                    setCurrentDate={setCurrentDate}
                                    selectedDate={selectedDate}
                                    setSelectedDate={setSelectedDate}
                                    setNewSessionStart={handleNewSessionStart}
                                    onSessionClick={handleSessionClick}
                                    variant="full"
                                />
                            </Tabs.Content>
                        </div>
                    </div>
                    {/* Mobile view - always shows monthly */}
                    <div className="flex flex-col md:hidden">
                        <MonthlyGroupCoachingCalendarWrapper
                            groupCoachingSessionsViewModel={groupCoachingSessionsViewModel}
                            coachCoachingSessionsViewModel={coachCoachingSessionsViewModel}
                            currentDate={currentDate}
                            setCurrentDate={setCurrentDate}
                            selectedDate={selectedDate}
                            setSelectedDate={setSelectedDate}
                            setNewSessionStart={handleNewSessionStart}
                            onSessionClick={handleSessionClick}
                        />
                    </div>
                </div>
            </Tabs.Root>
        </div>
    );
}

export default function AddGroupSession({ locale, courseSlug, groupId }: AddGroupSessionProps) {
    const { data: session, status } = useSession();
    const router = useRouter();
    const currentLocale = useLocale() as TLocale;
    const breadcrumbsTranslations = useTranslations('components.breadcrumbs');
    const mainBreadcrumbsTranslations = useTranslations('components.breadcrumbs');
    const t = useTranslations('pages.addGroupSession');

    // Fetch group introduction to get group name and course title
    const [groupIntroductionResponse] = trpc.getGroupIntroduction.useSuspenseQuery({
        courseSlug: courseSlug,
        additionalParams: {
            groupId: parseInt(groupId),
            requestType: 'requestForCoach',
        },
    });
    const [groupIntroductionViewModel, setGroupIntroductionViewModel] =
        React.useState<viewModels.TGetGroupIntroductionViewModel | undefined>(undefined);
    const { presenter: introPresenter } = useGetGroupIntroductionPresenter(setGroupIntroductionViewModel);
    // @ts-ignore
    introPresenter.present(groupIntroductionResponse, groupIntroductionViewModel);

    // Loading state
    if (status === 'loading') {
        return <DefaultLoading locale={currentLocale} />;
    }

    // Authentication check - Coach only
    if (!session || !session.user?.roles?.includes('coach')) {
        return (
            <DefaultError
                type="simple"
                locale={currentLocale}
                title={t('error.unauthorized')}
                description={t('error.unauthorized')}
            />
        );
    }

    // Get group name and course title from introduction data (fallback to slug/id if not available)
    const groupName = groupIntroductionViewModel?.mode === 'default'
        ? groupIntroductionViewModel.data.name
        : `Group ${groupId}`;
    const courseTitle = groupIntroductionViewModel?.mode === 'default'
        ? groupIntroductionViewModel.data.course.title
        : courseSlug;

    return (
        <div className="flex flex-col space-y-2">
            <Breadcrumbs
                items={[
                    {
                        label: breadcrumbsTranslations('home'),
                        onClick: () => router.push(`/${currentLocale}`),
                    },
                    {
                        label: breadcrumbsTranslations('workspace'),
                        onClick: () => router.push(`/${currentLocale}/workspace`),
                    },
                    {
                        label: breadcrumbsTranslations('yourCourses'),
                        onClick: () => router.push(`/${currentLocale}/workspace/courses`),
                    },
                    {
                        label: courseTitle,
                        onClick: () => router.push(`/${currentLocale}/courses/${courseSlug}`),
                    },
                    {
                        label: breadcrumbsTranslations('groups'),
                        onClick: () => router.push(`/${currentLocale}/courses/${courseSlug}?tab=groups`),
                    },
                    {
                        label: breadcrumbsTranslations('groupLabel').replace('{name}', groupName),
                        onClick: () => router.push(`/${currentLocale}/workspace/courses/${courseSlug}/groups/${groupId}`),
                    },
                    {
                        label: mainBreadcrumbsTranslations('groupCoachingCalendar'),
                        onClick: () => {
                            // Nothing should happen on clicking the current page
                        },
                    },
                ]}
            />
            <CalendarContent courseSlug={courseSlug} groupId={groupId} coachUsername={session.user?.name || ''} />
        </div>
    );
}
