'use client';

// Auto-generated by page-scaffold command v2
// Notion: https://www.notion.so/Become-a-coach-06c36feec8e340c79ca65f79971f1a20
// Usecases from Notion: listTopics, sendBecomeACoachEmail
// Features from Notion: listTopics, sendBecomeACoachEmail (client-side only - NOT YET IMPLEMENTED - use mailto link)
// API Endpoints from Notion:
// User Types from Notion: Visitor
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=6247-208046

import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';

interface BecomeACoachProps {
  locale: TLocale;
}

export default function BecomeACoach({ locale }: BecomeACoachProps) {
  const t = useTranslations('pages.becomeACoach');
  const currentLocale = useLocale() as TLocale;

  return (
    <div className="flex flex-col space-y-5 px-30">
      <div>
        <h1>{t('title')}</h1>
        <p>{t('description')}</p>
      </div>

      {/* Features from Notion:
        - listTopics
        - sendBecomeACoachEmail (client-side only - NOT YET IMPLEMENTED - use mailto link)
      */}
      {/* UI Components from Notion:
        - UserProfile (Personal information Form)
        - UserProfile (Professional Information Form)
        - Become a Coach Form (variant of UserProfile just with professional information form)
        - Professional Information Sent Modal
      */}

      {/* IMPORTANT NOTE from requirements:
        The feature SendBecomeACoachEmail is not there yet, but in the meanwhile
        put a note somewhere saying that for now we'll just do a mail-to link that
        pre-populates a message with all the data inputted in the form
      */}
      <div className="bg-yellow-100 border-l-4 border-yellow-500 p-4">
        <p className="text-sm">{t('mailtoNote')}</p>
      </div>
    </div>
  );
}
