'use client';

// Auto-generated by page-scaffold command v2 - Refactored
// Notion: https://www.notion.so/Received-payments-Orders-Payments-Coach-workspace-2925a7432d01807fb248fc457b865e8d
// Usecases from Notion: listUserOutgoingTransactions, generateInvoicePdf
// Features from Notion: View received payments from students, Generate/Download invoices
// User Types from Notion: Coach
// Figma: https://www.figma.com/design/8KEwRuOoD5IgxTtFAtLlyS/Just_Do_Ad-1.2?node-id=7709-235261

import { useLocale, useTranslations } from 'next-intl';
import { TLocale } from '@maany_shr/e-class-translations';
import { trpc } from '../trpc/cms-client';

interface ReceivedPaymentsTabProps {
  locale: TLocale;
}

export default function ReceivedPaymentsTab({ locale }: ReceivedPaymentsTabProps) {
  const t = useTranslations('pages.receivedPayments');
  const currentLocale = useLocale() as TLocale;

  // TRPC query for listUserOutgoingTransactions usecase
  const [transactionsResponse] = trpc.listUserOutgoingTransactions.useSuspenseQuery({});

  return (
    <div className="flex flex-col space-y-5">
      {/* Page header with translations */}
      <div>
        <h2 className="text-2xl font-semibold">{t('title')}</h2>
        <p className="text-gray-600">{t('description')}</p>
      </div>

      {/* Features from Notion:
        - View received payments from students
        - Generate/Download invoices
      */}
      {/* TODO: Implement client-side generateInvoicePdf */}
      {/* TODO: Add transaction table/grid with columns: transactionId, date, amount, status, type, from */}
      {/* TODO: Add generate/download invoice buttons */}
    </div>
  );
}
